'use client'

import { useEffect, useState } from 'react'
import { Luggage, Moon, Star, Sun, Tag, UserRound } from 'lucide-react'
import { answerLuggage, askLuggage, continueLuggage, initialLuggage, inspectLuggage, labelLuggage, luggageBags, luggageClaims, luggageFacts, luggageOnBelt, luggagePeople, luggageQuestions, luggageTransferStep, luggageValues, markLuggageFact, openLuggagePocket, sendLuggage, storeLuggage, takeLuggage, verifyLuggage } from '@/lib/luggage-mission'
import { Frame, useMission } from './mission-shared'
import s from './luggage-mission.module.css'

const colours: Record<string, string> = { blue: '#377eb1', green: '#538866', red: '#bd655d', yellow: '#c5a24e', black: '#34494a' }
function Bag({ id, label, detailed = false }: { id: number; label: number; detailed?: boolean }) {
  const bag = luggageBags[id], Sticker = bag.sticker === 'moon' ? Moon : bag.sticker === 'star' ? Star : Sun
  return <span className={s.bag} data-size={bag.size}><span className={s.case} style={{ background: colours[bag.colour] }}><span className={s.handle} aria-hidden="true"/><i style={{ background: colours[bag.strap] }}/>{detailed && <Sticker className={s.sticker} size={17}/>}</span>{detailed && <span className={s.wheels} aria-label={`${bag.wheels} wheels`}>{Array.from({ length: bag.wheels }, (_, i) => <i key={i}/>)}</span>}<strong>{bag.size} · {bag.colour}</strong><small>{bag.strap} strap{detailed ? ` · ${bag.wheels} wheels` : ''}</small><span className={s.tag}><Tag size={12}/>{luggagePeople[label]}</span></span>
}
export function LuggageMission() {
  const m = useMission('luggage-v1-eng-luggage', initialLuggage), v = m.state, claim = luggageClaims[v.claim]
  const [panel, setPanel] = useState<string | null>(null)
  const activePanel = panel ?? (v.selected < 0 ? 'belt' : v.verified < 0 ? 'desk' : 'handover')
  function take(bag: number) { m.update(takeLuggage(v, bag)); setPanel('desk') }
  function store(hold: boolean) { m.update(storeLuggage(v, hold)); setPanel('belt') }
  function advance() { const next = luggageTransferStep(v); m.update(next); if (!next.moving) setPanel(null) }
  const selected = v.selected, selectedBag = selected >= 0 ? luggageBags[selected] : null
  const busy = v.moving || v.partner, holds = v.positions.map((p, i) => p === 2 ? i : -1).filter(i => i >= 0)
  useEffect(() => {
    if (!m.ready || !v.moving || v.mode === 'show' || v.partner) return
    const timer = window.setTimeout(() => { const next = luggageTransferStep(v); m.update(next); if (!next.moving) setPanel(null) }, window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 40 : 420)
    return () => window.clearTimeout(timer)
  }, [m, v])
  return <>
    <Frame {...m} {...v} reset={() => { m.reset(); setPanel(null) }} phases={v.phase < 2 ? ['Open office', 'Two similar suitcases'] : ['Open office', 'Two similar suitcases', 'Another person receives']} resources={[`Issued by: ${v.delivered.length}`, `On check: ${luggagePeople[claim.owner]}`, `Corrections: ${v.attempts}`]} ending={v.feedback}>
      {v.phase === 0 ? <div><p>You work in a baggage office. Examine the suitcases, ask the owners about the details and compare the answers with the items. The suitcase can be set aside, its tag corrected and sent to the right person.</p><p>Two issues - short shift. After it, you can continue at home with a new condition. There is no timer.</p><div className={s.buttons}>{[['solo', 'Independently'], ['show', 'General screen'], ['coop', 'With a tutor']].map(([mode, label]) => <button key={mode} aria-pressed={v.mode === mode} onClick={() => m.update({ mode })}>{label}</button>)}</div><button className={s.primary} onClick={() => m.update({ phase: 1 })}>Open luggage office</button></div> : <>
        {v.mode === 'coop' && <div className={s.roles}><span>The student examines things; the tutor answers on behalf of the owner. One screen, common task.</span><button disabled={v.moving} onClick={() => m.update({ partner: !v.partner, question: -1 })}>{v.partner ? 'Give to student' : 'The role of the tutor'}</button></div>}
        {v.partner ? <section className={s.owner}><h3>{luggagePeople[claim.owner]} owner&apos;s role</h3><p lang="en">{claim.brief}</p>{v.question >= 0 ? <><strong lang="en">{luggageQuestions[v.question]}</strong><p lang="en">{claim.replies[v.question]}</p><button onClick={() => m.update(answerLuggage(v))}>Reply and pass on to the student</button></> : <p>Answer the student&apos;s questions. Do not give the suitcase number; the decision on extradition remains with him.</p>}</section> : <>
          <section className={s.request}><strong><UserRound size={17}/>{luggagePeople[claim.owner]} · {v.claim === 2 ? 'Message from the owner' : 'At the counter'}</strong><p lang="en">{claim.brief}</p><details><summary>Help with English</summary><p>{claim.translation}</p><p>owner - owner collect - pick up strap - belt larger than - more than front pocket - front pocket</p></details></section>
          {v.claim === 1 && <p className={s.event}>After pushing the cart, two removable tags got mixed up. The examined objects and notes were preserved.</p>}
          <nav className={s.tabs} aria-label="Jobs">{[["belt", "Tape"], ["desk", "Inspection"], ["handover", "Issue"]].map(([name, label]) => <button key={name} aria-pressed={activePanel === name} onClick={() => setPanel(name)}>{label}{name === "desk" && selected >= 0 ? " · 1" : ""}</button>)}</nav><div className={s.workplace} data-panel={activePanel}>
            <section className={s.rack} aria-label="Luggage belt"><div className={s.sectionTitle}><h3>Arrivals belt</h3><button disabled={busy || v.positions.filter(p => p === 0).length < 2} onClick={() => m.update({ belt: v.belt + 1 })}>Scroll feed →</button></div><div className={s.belt}>{luggageOnBelt(v).map(id => <button key={id} data-bag={id} disabled={busy} aria-label={`On the table: suitcase ${id + 1}`} onClick={() => take(id)}><Bag id={id} label={v.tags[id]} detailed={v.inspected.includes(id)}/></button>)}{!luggageOnBelt(v).length && <p>The feed is empty. Check your pending items.</p>}</div>
              <div className={s.hold}><h4>Holding shelf · put aside</h4>{holds.length ? holds.map(id => <button key={id} aria-label={`Return to table: suitcase ${id + 1}`} disabled={busy} onClick={() => take(id)}><Bag id={id} label={v.tags[id]} detailed={v.inspected.includes(id)}/>{v.pockets.includes(id) && <small>Front pocket: {luggageBags[id].pocket}</small>}<span>Return to table: suitcase {id + 1}</span></button>) : <p>You can leave your suitcase here for comparison.</p>}</div>
              {!!v.delivered.length && <div className={s.history}><h4>Collected · already issued</h4>{v.delivered.map(id => <div key={id}><Luggage size={id === 0 ? 23 : 30}/><span>{luggagePeople[id]} · {luggageBags[id].size}, {luggageBags[id].colour}</span></div>)}</div>}
            </section>
            <section className={s.desk} aria-label="Examination table"><h3>Inspection desk</h3><details className={s.questions}><summary>Ask the owner · clarify description</summary><div className={s.buttons}>{luggageQuestions.map((q, i) => <button key={q} disabled={busy} aria-pressed={v.asked.includes(i)} onClick={() => m.update(askLuggage(v, i))}>{q}</button>)}</div>{v.asked.length > 0 && <div className={s.notes}>{v.asked.map(i => <p key={i} lang="en"><strong>{luggageQuestions[i]}</strong><br/>{claim.replies[i]}</p>)}</div>}</details>{selectedBag ? <><Bag id={selected} label={v.tags[selected]} detailed={v.inspected.includes(selected)}/><div className={s.buttons}><button disabled={busy} onClick={() => m.update(inspectLuggage(v))}>Turn the case around</button><button disabled={busy} onClick={() => m.update(openLuggagePocket(v))}>Open the front pocket</button><button disabled={busy} onClick={() => store(true)}>Set aside for comparison</button><button disabled={busy} onClick={() => store(false)}>Return to tape</button></div>{v.claim !== 2 && v.pockets.includes(selected) && <p className={s.pocket} lang="en">Front pocket: <strong>{selectedBag.pocket}</strong></p>}<p>{v.claim === 2 ? "The gift is sealed. Choose two external signs from Leo's message." : "Choose two features for verification: one external and the contents of the pocket."}</p><div className={s.facts}>{luggageFacts.map((fact, i) => <button key={fact} disabled={busy || (i === 5 ? v.claim === 2 || !v.pockets.includes(selected) : [2, 4].includes(i) && !v.inspected.includes(selected))} aria-pressed={v.evidence.includes(i)} data-evidence={i} onClick={() => m.update(markLuggageFact(v, i))}><small>{fact}</small><strong>{i === 5 && (v.claim === 2 || !v.pockets.includes(selected)) || [2, 4].includes(i) && !v.inspected.includes(selected) ? '?' : luggageValues(selected)[i]}</strong></button>)}</div><button className={s.primary} disabled={busy} onClick={() => m.update(verifyLuggage(v))}>Check selected features</button>{v.verified === selected && <div className={s.verified}><p>✓ Two signs are confirmed.</p><button onClick={() => setPanel("handover")}>Apply for issuance →</button></div>}</> : <p>Take the suitcase from the belt or shelf. The unnecessary item will remain in the bureau, and your notes will be preserved.</p>}</section>
          </div>
          <section className={s.handover} data-active={activePanel === "handover"} aria-label="Registration of issue"><h3>Label and collection</h3>{selected >= 0 && <p className={s.labelPreview}><Tag size={16}/> Suitcase {selected + 1} · {luggageBags[selected].colour}<br/>On the tag: <strong>{luggagePeople[v.tags[selected]]}</strong></p>}<div className={s.paperwork}><label>Owner on the label<select aria-label="Owner on the label" disabled={busy || v.verified < 0} value={v.label} onChange={e => m.update({ label: Number(e.target.value) })}><option value={-1}>Select owner</option>{luggagePeople.slice(0, 4).map((name, i) => <option key={name} value={i}>{name}</option>)}</select></label><button disabled={busy || v.verified < 0 || v.label < 0} onClick={() => m.update(labelLuggage(v))}>Print and attach label</button><label>Collected by<select aria-label="Collected by" disabled={busy} value={v.collector} onChange={e => m.update({ collector: Number(e.target.value) })}><option value={-1}>Who gets it?</option>{luggagePeople.slice(0, 4).map((name, i) => <option key={name} value={i}>{name}</option>)}</select></label></div><div className={s.transfer} aria-label="Path to recipient" data-moving={v.moving}><span>Desk</span><span>Transfer belt</span><span>Collection</span>{v.selected >= 0 && <Luggage size={25} style={{ left: `${5 + v.transfer * 40}%` }}/>}</div><div className={s.buttons}><button className={s.primary} disabled={busy || selected < 0} onClick={() => m.update(sendLuggage(v))}>Send to collection</button>{v.moving && v.mode === 'show' && <button onClick={advance}>Next issuance step</button>}</div></section>
          <p className={s.feedback} role="status" lang="en">{v.feedback || 'A customer is waiting. Start with the description, then choose a case to inspect.'}</p>
        </>}
      </>}
    </Frame>
    {v.done && v.claim === 1 && <section className={s.continue}><h3>Short shift completed</h3><p>Continued: Leo can&apos;t come by himself. Remaining luggage and corrected tags will be retained.</p><button onClick={() => { m.update(continueLuggage(v)); setPanel(null) }}>Help the next owner · continue at home</button></section>}
  </>
}
