'use client'

import { useState } from 'react'
import { bridgeSpec, cargo, checkCargo, checkExpeditionBridge, checkPower, checkReactor, operations, runReactor, stationReserve, stormTurn, sum, buildingBlocked, checkBuilding, checkRoads, districtMetrics, districtPath, transitEdges, transitNodes, checkTransit, checkDeparture, lineNodes } from '@/lib/scenario-missions'
import { Brief, Choice, Frame, Go, Grid, NumberField, toggle, useMission } from './mission-shared'
import s from './missions.module.css'

export function ExpeditionMission() {
  const m = useMission('expedition', { phase: 0, done: false as boolean, route: 0, beams: [] as number[], anchors: 0, predicted: 0, slots: [-1, -1, -1, -1], weights: [0, 0, 0], repaired: false })
  const [trial, setTrial] = useState(false), [lastTrial, setLastTrial] = useState<number[]>([])
  const v = m.state, storm = v.phase === 3, spec = bridgeSpec(v.route, storm), cost = sum(v.beams) + v.anchors * 2
  const build = v.phase === 1 || (storm && v.route === 0 && !v.repaired)
  const editWeight = (i: number, n: number) => { setTrial(false); m.update({ weights: v.weights.map((w, j) => i === j ? n : w) }) }
  return <Frame {...m} {...v} reset={() => { m.reset(); setTrial(false); setLastTrial([]) }} phases={['Intelligence', 'Crossing', 'Cargo', 'After the storm']} resources={[`Materials: ${14 - cost}/14`, `Route: ${v.route === 0 ? 'Lowland' : 'Pass'}`, `Weight: 12 kg`]} ending={`All four boxes have been delivered. ${v.route === 0 ? 'You expanded the flooded crossing while preserving the cargo.' : 'You transferred the load to three carts after the upper road was damaged.'} Remaining ${14 - cost} materials.`}>
    {v.phase === 0 && <><Brief><p>You need to deliver water, food, tools and a walkie-talkie to the camp. Scouts offer two options. Read the forecast: it will affect the last part of the mission.</p></Brief><div className={s.two}><Choice title="Lowland · bridge 6 m" selected={v.route === 0} onClick={() => m.update({ route: 0 })}>Short crossing. After rain, the riverbed will widen by 2 m. We will have to complete the bridge from the remaining materials.</Choice><Choice title="Pass · bridge 8 m" selected={v.route === 1} onClick={() => m.update({ route: 1 })}>The riverbed does not change. After the storm, only three 5 kg carts will remain on the detour.</Choice></div><Go onClick={() => m.update({ phase: 1 })}>Select route</Go></>}
    {build && <><Brief><p>{storm ? 'The rain raised the water. Understand the same design: the beams can be removed and reused.' : 'Build a bridge exactly the width of the riverbed. Parts are returned to the warehouse when removed.'}</p><p>Span <b>{spec.span} m</b>. A meter of beam costs 1 material; fastening - 2. There are two beams of each size in stock. Four boxes weigh 12 kg; they need to be transported on two trolleys without separating the boxes. Trolley limit: 2 + 2 × number of fastenings kg.</p></Brief><div className={s.bridge} aria-label="Bridge design"><span>Shore</span><div>{v.beams.length ? v.beams.map((n, i) => <button key={i} aria-label={`Remove the beam ${i + 1}`} style={{ flexGrow: n }} onClick={() => m.update({ beams: v.beams.filter((_, j) => i !== j) })}>{n} m ×</button>) : <p>Add beams</p>}</div><span>Shore</span></div><div className={s.row}>{[2, 3, 4].map(n => <button key={n} disabled={v.beams.filter(b => b === n).length >= 2} onClick={() => m.update({ beams: [...v.beams, n] })}>Beam {n} m · left {2 - v.beams.filter(b => b === n).length}</button>)}</div><div className={s.inputs}><NumberField label="Fastenings" value={v.anchors} max={2} onChange={anchors => m.update({ anchors })} /><NumberField label="Trolley limit, kg" value={v.predicted} onChange={predicted => m.update({ predicted })} /></div><Go onClick={() => m.check(checkExpeditionBridge(v.route, storm, v.beams, v.anchors, v.predicted), storm ? { repaired: true } : { phase: 2 })}>{storm ? 'Test the completed bridge' : 'Test the bridge'}</Go></>}

    {(v.phase === 2 || (storm && (v.route === 1 || v.repaired))) && <><Brief><p>{storm ? v.route === 0 ? 'The bridge has been widened. Before departure, check the manifest - the cargo is already secured on the selected trolleys.' : 'The upper road is damaged. A change is needed: now there are three carts, and each can only support 5 kg. Boxes cannot be divided.' : 'Distribute all the boxes into two carts. Prepare a weight sheet before your test flight.'}</p><p>Limit: <b>{storm && v.route === 1 ? 5 : 2 + 2 * v.anchors} kg</b> on the cart.</p></Brief><div className={s.cargo}>{cargo.map((c, i) => <label key={c.name}><strong>{c.name} · {c.weight} kg</strong><select aria-label={`Trolley: ${c.name}`} value={v.slots[i]} onChange={e => { setTrial(false); m.update({ slots: v.slots.map((slot, j) => i === j ? Number(e.target.value) : slot), weights: [0, 0, 0] }) }}><option value={-1}>In stock</option>{Array.from({ length: spec.sleds }, (_, n) => <option key={n} value={n}>Trolley {n + 1}</option>)}</select></label>)}</div><div className={s.inputs}>{Array.from({ length: spec.sleds }, (_, i) => <NumberField key={i} label={`Trolley weight ${i + 1}`} value={v.weights[i]} onChange={n => editWeight(i, n)} />)}</div><section className={s.loadTrial} aria-label="Trolley test bench">
      <p>First, predict the masses in the statement. Then check how the load is distributed on the carts.</p>
      <button disabled={v.slots.some(slot => slot < 0) || v.weights.slice(0, spec.sleds).some(weight => !Number.isFinite(weight) || weight <= 0)} onClick={() => { setTrial(!trial); if (!trial) setLastTrial(Array.from({ length: spec.sleds }, (_, i) => [v.weights[i], sum(cargo.filter((_, j) => v.slots[j] === i).map(c => c.weight))]).flat()) }}>{trial ? 'Hide scale readings' : 'Check the forecast on the scales'}</button>
      {!!lastTrial.length && <p>Last try: {Array.from({ length: lastTrial.length / 2 }, (_, i) => `trolley ${i + 1}: forecast ${lastTrial[i * 2]} → scales ${lastTrial[i * 2 + 1]} kg`).join('; ')}. {trial ? 'Compare the forecast with the result.' : 'For a new distribution, enter a new forecast.'}</p>}
      <div className={s.loadCarts}>{Array.from({ length: spec.sleds }, (_, i) => { const boxes = cargo.filter((_, j) => v.slots[j] === i), weight = sum(boxes.map(c => c.weight)), limit = storm && v.route === 1 ? 5 : 2 + 2 * v.anchors; return <div key={i} data-over={trial && weight > limit}>
        <strong>Trolley {i + 1}</strong><div className={s.crates}>{boxes.map(c => <span key={c.name}>{c.name}<b>{c.weight} kg</b></span>)}</div>
        {trial ? <><meter min={0} max={12} high={limit} optimum={0} value={weight} aria-label={`Cart load ${i + 1}`}/><p>{weight} / {limit} kg · {weight > limit ? 'Overload: the trolley has stopped' : 'Wheels are being tested'}</p></> : <p>Limit {limit} kg · scale readings are hidden</p>}
      </div> })}</div>
    </section><Go onClick={() => m.check(checkCargo(v.route, storm, v.anchors, v.slots, v.weights), storm ? { done: true } : { phase: 3 })}>{storm ? 'Deliver the goods' : 'Send a test flight'}</Go>{v.phase === 2 && <button className={s.back} onClick={() => m.update({ phase: 1 })}>Change design</button>}</>}
  </Frame>
}

export function StationMission() {
  const m = useMission('station', { phase: 0, done: false as boolean, chain: [] as number[], fuel: 4, wiring: 0, allocation: [0, 0, 0], reserve: 0, turn: 0, oxygen: 0, shield: 0, history: [] as number[] })
  const v = m.state
  return <Frame {...m} {...v} phases={['Reactor repair', 'Power network', 'Solar storm']} resources={[`Fuel: ${v.phase === 0 ? 8 : 8 - v.fuel - v.wiring}`, `Output: ${runReactor(v.fuel, v.chain)}`, `Reserve: ${v.reserve}`]} ending={`The station experienced three pulses. Spent along the way ${v.history.join(' + ')} energy left ${v.reserve}. The order of the modules determined the output; network design and launch size - emergency reserve.`}>
    {v.phase === 0 && <><Brief><p>The reactor went offline before the storm. According to his passport, he fulfills <b>y = 3(x + 2)</b>. Assemble the two modules in the correct order. The test bench does not consume fuel.</p><p>There are 8 fuel cells on board. Running on 4 or 6 cells will give different output; the remaining cells will later turn into reserves of 4 energy each.</p></Brief><div className={s.flow}><span>x</span>{v.chain.map((id, i) => <button key={i} aria-label={`Remove module ${i + 1}`} onClick={() => m.update({ chain: v.chain.filter((_, j) => i !== j) })}>{operations[id]} ×</button>)}<span>→ y</span></div><div className={s.row}>{operations.map((op, i) => <button key={op} disabled={v.chain.length >= 2} onClick={() => m.update({ chain: [...v.chain, i] })}>{op}</button>)}</div><div className={s.samples}>{[2, 4, 6].map(n => <div key={n}>Login {n}<strong>{runReactor(n, v.chain)}</strong><small>Needed {(n + 2) * 3}</small></div>)}</div><div className={s.two}>{[4, 6].map(n => <Choice key={n} title={`Launch on ${n} cells`} selected={v.fuel === n} onClick={() => m.update({ fuel: n })}>Production according to the assembled scheme: {runReactor(n, v.chain)}. Fuel remaining: {8 - n}.</Choice>)}</div><Go onClick={() => m.check(checkReactor(v.chain), { phase: 1 })}>Check and run</Go></>}
    {v.phase === 1 && <><Brief><p>Distribute food into three compartments. Starting requires a minimum of 6 / 4 / 4 energy. The extra supply is wasted without benefit. Once launched, three turns of the storm will begin: keep at least 12 in reserve.</p></Brief><div className={s.two}><Choice title="Direct wiring" selected={v.wiring === 0} onClick={() => m.update({ wiring: 0 })}>Loses 4 energy. Does not require a fuel cell for setup.</Choice><Choice title="Stabilizer" selected={v.wiring === 1} onClick={() => m.update({ wiring: 1 })}>Loses 2 energy. To configure, it consumes 1 more fuel cell.</Choice></div><div className={s.network}><div className={s.source}>Reactor<br /><b>{runReactor(v.fuel, v.chain)}</b></div><div className={s.branch}>{['Oxygen', 'Communication', 'Shield'].map((name, i) => <NumberField key={name} label={`${name} · minimum ${[6, 4, 4][i]}`} value={v.allocation[i]} onChange={n => m.update({ allocation: v.allocation.map((a, j) => i === j ? n : a) })} />)}</div></div><p>After losses available {runReactor(v.fuel, v.chain) - (v.wiring === 0 ? 4 : 2)}. Submit Now {sum(v.allocation)}. Future reserve {stationReserve(v.fuel, v.wiring, v.allocation)}.</p><Go onClick={() => m.check(checkPower(v.fuel, v.wiring, v.allocation), { phase: 2, reserve: stationReserve(v.fuel, v.wiring, v.allocation) })}>Enable bays</Go><button className={s.back} onClick={() => m.update({ phase: 0 })}>Recalculate launch</button></>}
    {v.phase === 2 && <><Brief><p>Storm, move <b>{v.turn + 1} out of 3</b>. The reactor is turned off; We use only the accumulated reserve. On each turn, oxygen needs 2 energy, shield - according to the forecast.</p><p>You can test without penalty. A successful move actually uses up the stock and changes the next objective.</p></Brief><div className={s.forecast}>{[1, 3, 2].map((n, i) => <div key={i} data-current={v.turn === i}><small>Move {i + 1} {i < v.turn ? '✓' : ''}</small><strong>Oxygen 2</strong><span>Shield {n}</span></div>)}</div><div className={s.inputs}><NumberField label="Energy to oxygen" value={v.oxygen} onChange={oxygen => m.update({ oxygen })} /><NumberField label="Energy shield" value={v.shield} onChange={shield => m.update({ shield })} /></div><Go onClick={() => m.check(stormTurn(v.turn, v.reserve, v.oxygen, v.shield), { reserve: v.reserve - v.oxygen - v.shield, turn: Math.min(2, v.turn + 1), history: [...v.history, v.oxygen + v.shield], oxygen: 0, shield: 0, done: v.turn === 2 })}>Make a move</Go></>}
  </Frame>
}

export function DistrictMission() {
  const m = useMission('district', { phase: 0, done: false as boolean, building: [] as number[], roads: [] as number[], area: 0, perimeter: 0, flood: -1, drain: false })
  const v = m.state, metrics = districtMetrics(v.building, v.roads, v.drain)
  function click(cell: number) {
    if (v.phase === 0) { if (!buildingBlocked.includes(cell)) m.update({ building: toggle(v.building, cell) }) }
    else if (!v.building.includes(cell) && !buildingBlocked.includes(cell)) m.update({ roads: toggle(v.roads, cell) })
  }
  return <Frame {...m} {...v} phases={['Clinic plan', 'Login access', 'Shower']} resources={[v.phase === 0 ? 'Budget: 42 · estimate after inspection' : `Estimate: ${metrics.cost}/42`, `Clinic: ${v.building.length}/6 cells`, `Track: ${v.roads.length} cells`]} ending={`The clinic is open even after a rainstorm. You ${v.drain ? 'built a drainage system' : 'found a dry way'}, maintaining access from entry. Remaining budget ${42 - metrics.cost}. Try a different building shape: it will change the cost and the road.`}>
    <Brief><p>{v.phase === 0 ? 'Allocate 6 neighboring cells to the clinic. One cell - 1 m², side - 1 m. Construction: 2 per floor cell + 1 per meter of external wall. The rocks and entrance cannot be occupied. Leave two cells next to the entrance for a path.' : v.phase === 1 ? 'Create a path from the entrance to either side of the clinic. A track cell costs 2. Pressing again removes the cell and returns its value. During a rainstorm, one cell of the track will be flooded.' : 'The downpour flooded the marked square. Choose: save the route and buy a drainage system for 4 or make a detour. The clinic and original paths remain in place.'}</p></Brief>
    <div className={`${s.boardAndTools} ${s.districtGrid}`}><Grid label="Quarter plan" onCell={click} cells={Array.from({ length: 25 }, (_, i) => ({ style: v.building.includes(i) ? { borderWidth: 3, borderStyle: 'solid', borderTopColor: v.building.includes(i - 5) ? 'transparent' : '#315f43', borderBottomColor: v.building.includes(i + 5) ? 'transparent' : '#315f43', borderLeftColor: i % 5 > 0 && v.building.includes(i - 1) ? 'transparent' : '#315f43', borderRightColor: i % 5 < 4 && v.building.includes(i + 1) ? 'transparent' : '#315f43' } : undefined, text: i === 20 ? 'Entry' : [7, 17].includes(i) ? 'Rock' : v.building.includes(i) ? 'K' : i === v.flood ? v.drain ? '≈✓' : '≈' : v.roads.includes(i) ? '·' : '', type: i === v.flood && !v.drain ? 'water' : v.building.includes(i) ? 'building' : v.roads.includes(i) || i === 20 ? 'road' : [7, 17].includes(i) ? 'blocked' : '', label: `Cage ${i % 5}; ${4 - Math.floor(i / 5)}${v.building.includes(i) ? ', clinic' : ''}`, disabled: buildingBlocked.includes(i) || (v.phase > 0 && v.building.includes(i)) }))} />
    <div><p className={s.legend}>K - clinic · dot - path · ≈ - water.<br />Click the cells to build and remove. The dark line shows the outer walls; internal sides between cells are not paid.</p>{v.phase === 0 ? <div className={s.inputs}><NumberField label="Area, m²" value={v.area} onChange={area => m.update({ area })} /><NumberField label="External perimeter, m" value={v.perimeter} onChange={perimeter => m.update({ perimeter })} /></div> : <p>Gender {metrics.area * 2} + walls {metrics.perimeter} + tracks {v.roads.length * 2}{v.drain ? ' + drainage 4' : ''} = <b>{metrics.cost}</b></p>}{v.phase === 2 && <Choice title={v.drain ? 'Drainage installed · 4' : 'Install drainage · 4'} selected={v.drain} onClick={() => m.update({ drain: !v.drain })}>Protects a flooded cell. Click again to return the budget.</Choice>}</div></div>
    <Go onClick={() => {
      if (v.phase === 0) m.check(checkBuilding(v.building, v.area, v.perimeter), { phase: 1 })
      else if (v.phase === 1) {
        if (!v.roads.length) m.check({ ok: false, message: 'The entrance area requires at least one square of the path between the entrance and the clinic.' })
        else { const path = districtPath(v.building, v.roads, -1, false); m.check(checkRoads(v.building, v.roads, -1, false), { phase: 2, flood: path[Math.floor(path.length / 2)] ?? -1 }) }
      } else m.check(checkRoads(v.building, v.roads, v.flood, v.drain), { done: true })
    }}>{v.phase === 0 ? 'Agree on the estimate' : v.phase === 1 ? 'Open a clinic' : 'Check the path after a rainstorm'}</Go>
    {v.phase === 1 && <button className={s.back} onClick={() => m.update({ phase: 0, roads: [] })}>Rebuild the clinic</button>}
  </Frame>
}

export function TransitMission() {
  const m = useMission('transit', { phase: 0, done: false as boolean, line: 0, a: [] as number[], b: [] as number[], cars: [1, 1], departure: [0, 0], round: 0 })
  const v = m.state, lines = [v.a, v.b], cost = sum([...new Set([...v.a, ...v.b])].map(i => transitEdges[i].cost))
  const positions = [[35, 110], [130, 35], [250, 35], [135, 185], [350, 110], [270, 185]]
  return <Frame {...m} {...v} phases={['Route network', 'First flight', 'The bridge is closed', 'New schedule']} resources={[`Network: ${cost}/${v.round ? 13 : 9}`, `Cars: ${sum(v.cars)}/5`, `Day ${v.round + 1}`]} ending={`Both lines carried passengers after the bridge was closed. You redistributed the cars to meet the changing demand and coordinated departures on the common road. Built on ${cost} out of 13.`}>
    <Brief><p>{v.round === 0 ? 'Two lines leave the depot. A serves the school and park, B serves the market and home. Five carriages are divided between them, each with two seats.' : 'The Market-House road is closed. Line B now has a clinic, Line A has a longer line. The budget for reconstruction has been increased to 13. The old road can be dismantled with a full refund.'}</p><p>General trips are paid once. On each line, all necessary stops must be connected to a depot.</p></Brief>
    <svg className={s.transitMap} viewBox="0 0 400 230" role="img" aria-label="Network map. The stages are selected using the buttons below the map.">{transitEdges.map((e, i) => <g key={i}><line x1={positions[e.a][0]} y1={positions[e.a][1]} x2={positions[e.b][0]} y2={positions[e.b][1]} stroke={v.round === 1 && i === 4 ? '#bb645a' : v.a.includes(i) ? '#267753' : v.b.includes(i) ? '#376cab' : '#ced8d1'} strokeWidth={v.a.includes(i) || v.b.includes(i) ? 6 : 2} strokeDasharray={v.round && i === 4 ? '6 5' : undefined} />{v.a.includes(i) && v.b.includes(i) && !(v.round === 1 && i === 4) && <line x1={positions[e.a][0]} y1={positions[e.a][1]} x2={positions[e.b][0]} y2={positions[e.b][1]} stroke="#376cab" strokeWidth={6} strokeDasharray="7 7" />}<text x={(positions[e.a][0] + positions[e.b][0]) / 2} y={(positions[e.a][1] + positions[e.b][1]) / 2 - 7}>{e.cost}</text></g>)}{positions.map(([x, y], i) => <g key={i}><circle cx={x} cy={y} r={11} fill="#fff" stroke="#234d39" strokeWidth={2} /><text x={x} y={y + 28} textAnchor="middle">{transitNodes[i]}</text></g>)}</svg><p className={s.legend}>Green - A · blue - B · striped - general stage · red dotted line - closed.</p>
    {(v.phase === 0 || v.phase === 2) ? <><div className={s.row}>{['A school and park', 'B · market, house' + (v.round ? ', clinic' : '')].map((name, i) => <button key={name} aria-pressed={v.line === i} onClick={() => m.update({ line: i })}>Line {name}</button>)}</div><div className={s.edgeList}>{transitEdges.map((e, i) => <button key={i} aria-pressed={lines[v.line].includes(i)} onClick={() => m.update(v.line === 0 ? { a: toggle(v.a, i) } : { b: toggle(v.b, i) })}>{transitNodes[e.a]} — {transitNodes[e.b]}<small>{v.round && i === 4 ? 'Closed · remove' : `Cost ${e.cost}`} · {v.a.includes(i) ? 'A' : ''}{v.b.includes(i) ? 'B' : ''}</small></button>)}</div><Go onClick={() => {
      const req = v.round ? [[1, 2], [3, 4, 5]] : [[1, 2], [3, 4]]
      const connected = req.every((r, i) => r.every(n => lineNodes(lines[i]).has(n)))
      if (!connected) m.check({ ok: false, message: 'Check connections: each line must connect its stops to the depot.' })
      else if (cost > (v.round ? 13 : 9) || (v.round && lines.some(l => l.includes(4)))) m.check({ ok: false, message: 'The budget has been exceeded or a closed stage has been selected. Fix the network.' })
      else m.update({ phase: v.round ? 3 : 1 })
    }}>Go to departure</Go></> : <><div className={s.forecast}>{['A', 'B'].map((name, i) => <div key={name}><strong>Line {name}</strong><span>Queue: {(v.round ? [6, 4] : [4, 6])[i]}</span><NumberField label={`Cars ${name}`} value={v.cars[i]} max={5} onChange={n => m.update({ cars: v.cars.map((a, j) => i === j ? n : a) })} /><label>Departure {name}<select value={v.departure[i]} onChange={e => m.update({ departure: v.departure.map((a, j) => i === j ? Number(e.target.value) : a) })}><option value={0}>09:00</option><option value={2}>09:02</option></select></label></div>)}</div><p>If lines use at least one common stage, separate departures by 2 minutes. On a separate road you can start at the same time.</p><Go onClick={() => {
      const check = checkTransit(lines, v.cars, v.round)
      if (!check.ok) m.check(check)
      else if (!checkDeparture(lines, v.departure).ok) m.check(checkDeparture(lines, v.departure))
      else m.check(check, v.round ? { done: true } : { round: 1, phase: 2 })
    }}>Send trains</Go><button className={s.back} onClick={() => m.update({ phase: v.round ? 2 : 0 })}>Change network</button></>}
  </Frame>
}
