'use client'

import { checkRebooking, checkTimeline, checkTravel, formatTime, museumClues, travel, walkMuseum } from '@/lib/scenario-missions'
import { Brief, Choice, Frame, Go, Grid, NumberField, toggle, useMission } from './mission-shared'
import s from './missions.module.css'

const questions = [
  { ask: 'What time do we need to meet?', answer: 'By 3:10 pm at the latest. We need fifteen minutes to collect the box at the gallery.' },
  { ask: 'Is there anything I should know about the route?', answer: 'I have a heavy trolley. I cannot carry it up stairs, so we need step-free access.' },
  { ask: 'How much can we spend on transport?', answer: 'We have twelve pounds for the whole trip. We are starting at two o’clock.' },
  { ask: 'What is your favourite painting?', answer: 'I like landscapes. But first, let’s plan how to get there!' },
]
export function CityMission() {
  const m = useMission('city', { phase: 0, done: false as boolean, facts: [] as number[], reply: -1, method: 0, money: 0, arrival: 0, venue: 0, transfer: 0, slot: 60, words: [] as number[], sent: false, direction: -1 })
  const v = m.state
  const pieces = ['We are meeting', 'at the library', `at ${formatTime(v.slot)}`, 'because the gallery is closed.', 'at the gallery', 'before 14:00']
  return <Frame {...m} {...v} phases={['Conversation with Maya', 'First trip', 'New place', 'Agree']} resources={[`Time: ${v.phase < 2 ? '14:00' : formatTime(travel[v.method].minutes + 15)}`, `Money: £${v.phase < 2 ? 12 : 12 - travel[v.method].price - (v.phase === 3 && v.transfer === 1 ? 5 : 0)}`, `Plan: ${v.phase < 3 ? 'let\'s clarify' : 'Library Hall'}`]} ending={`You met at Library Hall in ${formatTime(v.slot)}. Route ${travel[v.method].name} → ${v.transfer === 0 ? 'on foot' : 'Shuttle'} maintained affordability and overall budget. Your message explained where, when and why the meeting is changing.`}>
    {v.phase === 0 && <><Brief><p>Maya asked for help with delivering a box for an exhibition. Before purchasing a ticket, find out the timing, route restrictions and budget. Questions and answers are part of the conversation.</p></Brief><blockquote lang="en">Hi! Can you help me collect a box and bring it to our meeting? We may need to change the plan if it rains.</blockquote><div className={s.dialogue}>{questions.map((q, i) => <button key={q.ask} lang="en" onClick={() => m.update({ reply: i, facts: v.facts.includes(i) ? v.facts : [...v.facts, i] })}>{q.ask}{v.facts.includes(i) ? ' ✓' : ''}</button>)}</div>{v.reply >= 0 && <blockquote lang="en">Maya: {questions[v.reply].answer}</blockquote>}<Go onClick={() => m.check({ ok: [0, 1, 2].every(i => v.facts.includes(i)), message: [0, 1, 2].every(i => v.facts.includes(i)) ? 'The terms have been collected. Choose the road that suits Maya.' : 'One of the conditions is missing: deadline, route restrictions or budget. Continue the conversation.' }, { phase: 1 })}>Create a route</Go></>}
    {v.phase > 0 && <details className={s.notebook}><summary>Correspondence and terms</summary>{v.facts.map(i => <p key={i} lang="en">{questions[i].answer}</p>)}</details>}
    {v.phase === 1 && <><Brief><p>It&apos;s 14:00 now. Choose transport to the gallery, then fill out the travel form. All prices are for both of you.</p></Brief><div className={s.options}>{travel.map((option, i) => <Choice key={option.name} title={`${option.name} · £${option.price} · ${option.minutes} min`} selected={v.method === i} onClick={() => m.update({ method: i })}>{option.accessible ? 'Step-free access.' : 'Lift out of order. Stairs only.'}</Choice>)}</div><div className={s.inputs}><NumberField label="There will be money left, £" value={v.money} onChange={money => m.update({ money })} /><NumberField label="Minutes on the way" value={v.arrival} onChange={arrival => m.update({ arrival })} /></div><Go onClick={() => m.check(checkTravel(v.method, v.money, v.arrival), { phase: 2 })}>Buy a ticket and go</Go></>}
    {v.phase === 2 && <><Brief><p>You received the box in 15 minutes. There&apos;s a new notice on the door. Save an available route and find a slot before the Maya deadline.</p></Brief><blockquote lang="en">Heavy rain: the gallery meeting room is closed. Please book another venue. Library Hall has step-free access. Roof Café is upstairs; there is no lift.</blockquote><div className={s.two}><Choice title="Library Hall" selected={v.venue === 0} onClick={() => m.update({ venue: 0 })}>Free · ground floor · bookings from 15:00.</Choice><Choice title="Roof Café" selected={v.venue === 1} onClick={() => m.update({ venue: 1 })}>Free · second floor · stairs only.</Choice></div><div className={s.two}><Choice title="Walk · 20 min · free" selected={v.transfer === 0} onClick={() => m.update({ transfer: 0 })}>Flat riverside path.</Choice><Choice title="Shuttle · 5 min · £5" selected={v.transfer === 1} onClick={() => m.update({ transfer: 1 })}>Step-free minibus.</Choice></div><label className={s.select}>Booking time<select value={v.slot} onChange={e => m.update({ slot: Number(e.target.value) })}>{[60, 65, 70].map(n => <option key={n} value={n}>{formatTime(n)}</option>)}</select></label><p>Now {formatTime(travel[v.method].minutes + 15)}. When you select the transfer, you will arrive at {formatTime(travel[v.method].minutes + 15 + (v.transfer === 0 ? 20 : 5))}.</p><Go onClick={() => m.check(checkRebooking(v.method, v.transfer, v.venue, v.slot), { phase: 3 })}>Book an appointment</Go></>}
    {v.phase === 3 && <><Brief><p>Inform Maya of the new location, time and reason for the transfer. Select the fragments in the desired order; Clicking on the selected fragment removes it from the message.</p></Brief>{!v.sent ? <><div className={s.sentence} aria-label="Your message">{v.words.length ? v.words.map((n, i) => <button key={i} lang="en" onClick={() => m.update({ words: v.words.filter((_, j) => i !== j) })}>{pieces[n]}</button>) : <span>Collect message here</span>}</div><div className={s.row}>{pieces.map((piece, i) => <button key={piece} disabled={v.words.includes(i)} lang="en" onClick={() => m.update({ words: [...v.words, i] })}>{piece}</button>)}</div><Go onClick={() => { const order = v.words.join(','); m.check({ ok: order === '0,1,2,3' || order === '0,2,1,3', message: order === '0,1,2,3' || order === '0,2,1,3' ? 'Maya: “Thanks! Which entrance should I use with the trolley?”' : 'Check the meaning: new place, confirmed time and reason. Start with We are meeting.' }, { sent: true }) }}>Send Maya</Go></> : <><blockquote lang="en">Maya: Thanks! Which entrance should I use with the trolley?</blockquote><div className={s.dialogue}>{['Use the riverside entrance. It is on the ground floor.', 'Take the stairs to the roof.', 'Go back to the gallery.'].map((text, i) => <Choice key={text} title={text} selected={v.direction === i} onClick={() => m.update({ direction: i })} />)}</div><Go onClick={() => m.check({ ok: v.direction === 0, message: v.direction === 0 ? 'Maya: “Perfect. See you there!”' : 'This entrance does not fit the cart or leads to the old location. Check the new address.' }, { done: true })}>Confirm login</Go></>}</>}
  </Frame>
}

export function MuseumMission() {
  const m = useMission('museum', { phase: 0, done: false as boolean, clues: [] as number[], tutor: false, camera: 0, exit: 0, locked: 0, conclusion: -1, evidence: [] as number[], program: [] as number[], walked: false })
  const v = m.state, walk = walkMuseum(v.program)
  return <Frame {...m} {...v} phases={['Gathering evidence', 'Real time', 'Version check', 'Courier']} resources={[`Evidence: ${v.clues.length}/4`, `Mode: ${v.tutor ? 'partner directory' : 'student'}`, `Courier steps: ${v.program.length}/12`]} ending="The exhibit was found in the restoration room. You corrected the camera time, checked the version with two sources and led the courier along a dry corridor. The contradiction turned out to be an error of the clock, not a deception of the witness.">
    <div className={s.role}><p>You can do it alone or together behind one screen. The student investigates and controls the courier; The tutor reads the handbook and explains the conditions.</p><button aria-pressed={v.tutor} onClick={() => m.update({ tutor: !v.tutor })}>{v.tutor ? 'Return to student' : 'Open partner directory'}</button></div>
    {v.tutor ? <aside className={s.manual}><h3>Warden&apos;s Handbook</h3><p lang="en">The camera clock is five minutes fast. Leo left one minute before the hall was locked.</p><p lang="en">The restoration room is at (4, 4). Start at (0, 0). The wet tiles are (1, 2), (2, 2), and (3, 2). North increases the second coordinate.</p><p>Give the student rules, not a ready-made sequence of steps. Alone, this guide is available as a hint.</p></aside> : <>
      {v.phase === 0 && <><Brief><p>The exhibit did not come to the exhibition. According to the camera, the box seemed to have entered the hall after closing. Check your sources and find out where to send the courier.</p></Brief><div className={s.two}>{museumClues.map((clue, i) => <button className={s.clue} key={clue.name} onClick={() => m.update({ clues: v.clues.includes(i) ? v.clues : [...v.clues, i] })}><strong>{clue.name}{v.clues.includes(i) ? ' ✓' : ''}</strong><span lang="en">{v.clues.includes(i) ? clue.text : 'Interview/inspect'}</span></button>)}</div><Go onClick={() => m.check({ ok: [0, 1, 2].every(i => v.clues.includes(i)), message: [0, 1, 2].every(i => v.clues.includes(i)) ? 'There is camera footage, a witness and a delivery address. First, figure out the timing.' : 'You need a camera, a witness and an invoice. The version based on only one source is unreliable.' }, { phase: 1 })}>Restore events</Go></>}
      {v.phase > 0 && <details className={s.notebook}><summary>Evidence log</summary>{v.clues.map(i => <p key={i} lang="en"><b>{museumClues[i].name}:</b> {museumClues[i].text}</p>)}</details>}
      {v.phase === 1 && <><Brief><p>Compare the readings. Enter the real minutes after 14:00. The Partner Handbook explains what&apos;s wrong with the watch and when Leo came out.</p></Brief><div className={s.timeline}><NumberField label="Entrance with box · 14:__" value={v.camera} max={59} onChange={camera => m.update({ camera })} /><span>→</span><NumberField label="Exit Leo · 14:__" value={v.exit} max={59} onChange={exit => m.update({ exit })} /><span>→</span><NumberField label="Closing · 14:__" value={v.locked} max={59} onChange={locked => m.update({ locked })} /></div><Go onClick={() => m.check(checkTimeline(v.camera, v.exit, v.locked), { phase: 2 })}>Check chronology</Go></>}
      {v.phase === 2 && <><Brief><p>Timeline: Entry 14:{v.camera}, output 14:{v.exit}, closing 14:{v.locked}. Select the next search point and two clues: one about the box leaving the hall, the second about its purpose.</p></Brief><div className={s.options}>{['In the locked eastern hall', 'In Mia\'s library', 'In the restoration'].map((name, i) => <Choice key={name} title={name} selected={v.conclusion === i} onClick={() => m.update({ conclusion: i })} />)}</div><div className={s.row}>{v.clues.map(i => <button key={i} aria-pressed={v.evidence.includes(i)} onClick={() => m.update({ evidence: toggle(v.evidence, i) })}>{museumClues[i].name}</button>)}</div><Go onClick={() => m.check({ ok: v.conclusion === 2 && v.evidence.length === 2 && v.evidence.includes(1) && v.evidence.includes(2), message: v.conclusion === 2 && v.evidence.length === 2 && v.evidence.includes(1) && v.evidence.includes(2) ? 'The caretaker confirms the exit, the invoice indicates the address. We send the courier to the restoration room.' : 'The case must be based on two specific pieces of evidence: exit before closing and delivery appointment.' }, { phase: 3 })}>Justify the route</Go></>}
      {v.phase === 3 && <><Brief><p>The courier starts at (0; 0). Make a program before the restoration (4; 4). The partner has the coordinates of the wet floor. After a test run, you will see at what step the problem occurred.</p></Brief><Grid label="Museum corridors" onCell={() => {}} cells={Array.from({ length: 25 }, (_, i) => ({ text: i === (v.walked ? walk.cell : 20) ? 'K' : i === 4 ? 'Goal' : v.walked && walk.visited.includes(i) ? '·' : '', label: `corridor ${i % 5}; ${4 - Math.floor(i / 5)}`, type: i === 4 ? 'building' : v.walked && walk.visited.includes(i) ? 'road' : '', disabled: true }))} /><div className={s.program}>{v.program.length ? v.program.map((n, i) => <button key={i} aria-label={`Delete step ${i + 1}`} onClick={() => m.update({ program: v.program.filter((_, j) => i !== j), walked: false })}>{i + 1}. {['↑ N', '→ E', '↓ S', '← W'][n]}</button>) : <p>The program is still empty</p>}</div><div className={s.row}>{['↑ North', '→ East', '↓ South', '← West'].map((label, i) => <button key={label} disabled={v.program.length >= 12} onClick={() => m.update({ program: [...v.program, i], walked: false })}>{label}</button>)}</div><Go onClick={() => { m.update({ walked: true }); m.check(walk, walk.ok ? { done: true } : undefined) }}>Launch courier</Go><button className={s.back} onClick={() => m.update({ program: [], walked: false })}>Clear program</button></>}
    </>}
  </Frame>
}
