'use client'

import { type Activity, type Workspace, type WorkshopMission, evaluateActivity, executeMachine, initialWorkspace, measure, mechanicNames, transformed, walk } from '@/lib/mission-workshop'
import { Brief, Frame, Go, Grid, NumberField, toggle, useMission } from './mission-shared'
import s from './missions.module.css'

const hints: Record<Activity['kind'], string> = {
  route: 'First find all the required points. Write down the route in parts and check where each part ends.',
  pack: 'Consider each indicator separately. A large set can replace several small ones; excess parts can be returned.',
  sequence: 'Find the beginning and the end. Then figure out which step cannot happen without the previous one. Check both the meaning and grammar of the text.',
  sort: 'First, formulate the rule for each department. If a card doesn\'t fit, check its meaning in the given context.',
  balance: 'Count each element on the left and right. Change the entire number of cards. Finally, reduce the overall odds factor.',
  machine: 'Pass one input through each module in order. Then be sure to check the remaining inputs.',
  experiment: 'Keep the second value, change the first. Compare how many times or how much the result has changed.',
  plot: 'Neighboring cells have a common side that is not included in the outer boundary. Compact forms usually require less fencing.',
  network: 'Start with node 0. Add connections to points that have not yet been connected. The loop can consume resource without connecting new nodes.',
  schedule: 'First, mark the unavailable intervals. Then put in the required previous papers. One stand does not perform two jobs at the same time.',
  transform: 'Watch the angle of the figure. Rotating around the center and flipping give different results. After this, correct the situation by transferring.',
  proof: 'Break the statement down into facts. For each, find a source that confirms it; remove irrelevant documents.',
}
function bankOrder(length: number, title: string) {
  const offset = 1 + (Array.from(title).reduce((n, c) => n + c.charCodeAt(0), 0) % Math.max(1, length - 1))
  return Array.from({ length }, (_, i) => (i + offset) % length).reverse()
}
const put = (values: number[], index: number, value: number) => values.map((v, i) => i === index ? value : v)

export function ActivityField({ activity: a, work, change }: { activity: Activity; work: Workspace; change: (patch: Partial<Workspace>) => void }) {
  const v = work.values
  switch (a.kind) {
    case 'route': {
      const walked = walk(a, v), cell = walked.path.at(-1)
      return <><p>K - courier · ● - obligatory point · C - target · × - closed. Limit {a.max} commands</p><Grid label="Route" onCell={() => {}} cells={Array.from({ length: 25 }, (_, i) => ({ text: i === cell ? 'K' : a.blocked.includes(i) ? '×' : i === a.goal ? 'C' : a.stops.includes(i) ? '●' : walked.path.includes(i) ? '·' : '', label: `Cage ${i}`, type: a.blocked.includes(i) ? 'blocked' : i === a.goal ? 'building' : walked.path.includes(i) ? 'road' : '', disabled: true }))} /><div className={s.program}>{v.map((cmd, i) => <button key={i} aria-label={`Delete command ${i + 1}`} onClick={() => change({ values: v.filter((_, j) => i !== j) })}>{i + 1}. {['↑','→','↓','←'][cmd]}</button>)}</div><div className={s.row}>{['North ↑','East →','South ↓','West ←'].map((name, i) => <button key={name} data-command={i} disabled={v.length >= a.max} onClick={() => change({ values: [...v, i] })}>{name}</button>)}</div>{walked.error && <p role="status">{walked.error}</p>}</>
    }
    case 'pack': {
      const sums = a.axes.map((_, axis) => a.items.reduce((n, item, i) => n + item.vector[axis] * (v[i] ?? 0), 0))
      return <><div className={s.forecast}>{a.axes.map((axis, i) => <div key={axis}><span>{axis}</span><strong>{sums[i]} / {a.target[i]}</strong></div>)}</div><div className={s.inventory}>{a.items.map((item, i) => <section key={item.name}><h3>{item.name}</h3><p>{a.axes.map((axis, j) => `${axis}: ${item.vector[j]}`).join(' · ')}</p><small>In stock {item.stock - (v[i] ?? 0)}</small><div className={s.stepper}><button aria-label={`Remove: ${item.name}`} disabled={!v[i]} onClick={() => change({ values: put(v, i, v[i] - 1) })}>−</button><output aria-label={`Taken: ${item.name}`}>{v[i] ?? 0}</output><button data-item={i} aria-label={`Take: ${item.name}`} disabled={v[i] >= item.stock} onClick={() => change({ values: put(v, i, v[i] + 1) })}>+</button></div></section>)}</div></>
    }
    case 'sequence': return <><div className={s.sentence} aria-label="Your consistency">{v.length ? v.map((card, i) => <button key={i} onClick={() => change({ values: v.filter((_, j) => i !== j) })}>{i + 1}. {a.cards[card]} ×</button>) : <p>Click the fragments in the desired order. The selected fragment can be removed.</p>}</div><div className={s.dialogue}>{bankOrder(a.cards.length, a.title).map(i => <button data-card={i} key={i} disabled={v.includes(i)} onClick={() => change({ values: [...v, i] })}>{a.cards[i]}</button>)}</div></>
    case 'sort': return <div className={s.sorting}>{a.cards.map((card, i) => <label key={card.text}><span>{card.text}</span><select data-sort={i} value={v[i] ?? -1} onChange={ev => change({ values: put(v, i, Number(ev.target.value)) })}><option value={-1}>Select a branch</option>{a.groups.map((group, j) => <option key={group} value={j}>{group}</option>)}</select></label>)}</div>
    case 'balance': return <><p>Change the odds before the cards. A minimum integer ratio is required.</p><div className={s.reaction}>{a.terms.map((term, i) => <div key={i}><span>{i === 0 ? '' : a.terms[i - 1].side !== term.side ? '→' : '+'}</span><NumberField label={`Coefficient ${i + 1}: ${term.name}`} value={v[i] ?? 1} min={1} max={12} onChange={n => change({ values: put(v, i, n) })} /><strong>{term.name}</strong></div>)}</div><div className={s.forecast}>{a.elements.map((element, j) => <div key={element}><span>{element}</span><strong>{a.terms.reduce((n, term, i) => n + (term.side > 0 ? term.atoms[j] * v[i] : 0), 0)} = {a.terms.reduce((n, term, i) => n + (term.side < 0 ? term.atoms[j] * v[i] : 0), 0)}</strong></div>)}</div></>
    case 'machine': return <><div className={s.flow}><span>Login →</span>{v.map((op, i) => <button key={i} aria-label={`Remove module ${i + 1}`} onClick={() => change({ values: v.filter((_, j) => i !== j) })}>{a.ops[op].name} ×</button>)}<span>→ Exit</span></div><div className={s.row}>{bankOrder(a.ops.length, a.title).map(i => <button key={i} data-op={i} disabled={v.length >= a.slots} onClick={() => change({ values: [...v, i] })}>{a.ops[i].name}</button>)}</div><div className={s.samples}>{a.inputs.map((input, i) => <div key={i}><span>Login: {input}</span><strong>{executeMachine(a, v, input)}</strong><small>Needed {a.outputs[i]}</small></div>)}</div></>
    case 'experiment': return <><div className={s.inputs}><label>{a.x}<select data-knob="x" value={v[0]} onChange={ev => change({ values: put(v, 0, Number(ev.target.value)) })}>{a.range.map(n => <option key={n} value={n}>{n}</option>)}</select></label><label>{a.y}<select data-knob="y" value={v[1]} onChange={ev => change({ values: put(v, 1, Number(ev.target.value)) })}>{a.range.map(n => <option key={n} value={n}>{n}</option>)}</select></label><button disabled={(a.domain === 'fraction' && v[0] > v[1]) || work.trace.length >= 24 || Array.from({ length: work.trace.length / 3 }, (_, i) => i * 3).some(i => work.trace[i] === v[0] && work.trace[i + 1] === v[1])} onClick={() => change({ trace: [...work.trace, v[0], v[1], measure(a, v[0], v[1])] })}>Conduct an experiment</button></div>{a.domain === 'fraction' && <p>The mass of the substance should not exceed the mass of the entire solution.</p>}<div className={s.labResults} role="table" aria-label="Experiment log"><div role="row"><b>{a.x}</b><b>{a.y}</b><b>Result</b></div>{Array.from({ length: work.trace.length / 3 }, (_, i) => <div role="row" key={i}><span>{work.trace[i * 3]}</span><span>{work.trace[i * 3 + 1]}</span><strong>{Number(work.trace[i * 3 + 2].toFixed(3))} {a.unit}</strong></div>)}</div><p>Make a forecast for {a.x} = {a.test[0]}, {a.y} = {a.test[1]}. We need at least two experiments in which only the first quantity changes.</p><NumberField label={`Forecast, ${a.unit}`} value={v[2]} max={9999} step="any" onChange={n => change({ values: put(v, 2, n) })} /><button className={s.back} onClick={() => change({ trace: [] })}>Start the series of experiments again</button></>
    case 'plot': return <><p>Area {a.area} cells border ≤ {a.fence}. ● required · × prohibited. Pressing again removes the cage.</p><Grid label="Plot" onCell={i => change({ values: toggle(v, i) })} cells={Array.from({ length: 25 }, (_, i) => ({ text: a.blocked.includes(i) ? '×' : a.required.includes(i) ? '●' : v.includes(i) ? '■' : '', label: `Plot ${i}`, type: a.blocked.includes(i) ? 'blocked' : v.includes(i) ? 'building' : '', disabled: a.blocked.includes(i) }))} /></>
    case 'network': {
      const points = [[45,100],[160,25],[160,175],[280,100]]
      return <><svg viewBox="0 0 330 220" className={s.transitMap} role="img" aria-label="Network of connections">{a.edges.map((edge, i) => <g key={i}><line x1={points[edge.a][0]} y1={points[edge.a][1]} x2={points[edge.b][0]} y2={points[edge.b][1]} stroke={a.blocked.includes(i) ? '#ba6760' : v.includes(i) ? '#287451' : '#d2d9ca'} strokeWidth={v.includes(i) ? 5 : 2} strokeDasharray={a.blocked.includes(i) ? '6 5' : undefined} /><text x={(points[edge.a][0] + points[edge.b][0]) / 2} y={(points[edge.a][1] + points[edge.b][1]) / 2 - 7}>{edge.cost}</text></g>)}{a.nodes.map((node, i) => <g key={node}><circle cx={points[i][0]} cy={points[i][1]} r={11} fill="white" stroke="#316649"/><text x={points[i][0]} y={points[i][1]+29} textAnchor="middle">{i}. {node}</text></g>)}</svg><p>Network cost: {v.reduce((sum, i) => sum + a.edges[i].cost, 0)} / {a.budget}. The red dotted line is an unavailable channel.</p><div className={s.edgeList}>{a.edges.map((edge, i) => <button key={i} data-edge={i} disabled={a.blocked.includes(i)} aria-pressed={v.includes(i)} onClick={() => change({ values: toggle(v, i) })}>{a.nodes[edge.a]} — {a.nodes[edge.b]}<small>{a.blocked.includes(i) ? 'Closed' : `Price ${edge.cost}`}</small></button>)}</div></>
    }
    case 'schedule': return <><p>One performer. Intervals from 0 to {a.horizon}; duration is given in conventional time units. Press the cell to start working.</p><div className={s.schedule}>{a.jobs.map((job, i) => <section key={job.name}><h3>{job.name} · {job.duration} units</h3><small>{job.after.length ? `After: ${job.after.map(j => a.jobs[j].name).join(', ')}` : 'No preliminary work'}</small><div className={s.timeSlots}>{Array.from({ length: a.horizon }, (_, hour) => <button key={hour} data-job={i} data-time={hour} disabled={a.blocked.includes(hour) || hour + job.duration > a.horizon} aria-label={`${job.name}: beginning ${hour}`} aria-pressed={v[i] === hour} data-occupied={v[i] >= 0 && hour >= v[i] && hour < v[i] + job.duration} onClick={() => change({ values: put(v, i, hour) })}>{a.blocked.includes(hour) ? '×' : hour}</button>)}</div></section>)}</div></>
    case 'transform': {
      const current = transformed(a, v) ?? [], names = ['Up','Right','Down','Left','Rotate 90°','Reflection']
      return <><p>■ — figure · ○ — target · ✓ — coincidence. Maximum {a.max} transformations.</p><Grid label="Shape Transformation" onCell={() => {}} cells={Array.from({ length: 25 }, (_, i) => ({ text: current.includes(i) && a.target.includes(i) ? '✓' : current.includes(i) ? '■' : a.target.includes(i) ? '○' : '', label: `Position ${i}`, type: current.includes(i) ? 'building' : a.target.includes(i) ? 'road' : '', disabled: true }))} /><div className={s.row}>{names.map((name, i) => <button key={name} data-transform={i} disabled={v.length >= a.max} onClick={() => change({ values: [...v, i] })}>{name}</button>)}</div><p>Moves: {v.map(i => names[i]).join(' → ') || 'not yet'}</p><button disabled={!v.length} onClick={() => change({ values: v.slice(0,-1) })}>Cancel conversion</button></>
    }
    case 'proof': return <><blockquote>{a.claim}</blockquote><p>Need to confirm: {a.facts.join('; ')}. Audit budget: {a.budget}.</p><div className={s.two}>{a.sources.map((source, i) => <section className={s.document} key={source.name}><button data-source={i} onClick={() => change({ seen: work.seen.includes(i) ? work.seen : [...work.seen, i] })}>{source.name} · check {source.cost}</button>{work.seen.includes(i) && <><p>{source.text}</p><button data-evidence={i} aria-pressed={v.includes(i)} onClick={() => change({ values: toggle(v, i) })}>{v.includes(i) ? 'Remove from evidence' : 'As proof'}</button></>}</section>)}</div></>
  }
}

export function WorkshopMissionView({ mission }: { mission: WorkshopMission }) {
  const m = useMission(`workshop-${mission.id}`, { phase: 0, done: false as boolean, reserve: 18, costs: [] as number[], values: [] as number[], trace: [] as number[], seen: [] as number[], passed: false, hints: 0, showHint: false, checks: 0 })
  const v = m.state, activity = mission.stages[Math.max(0, v.phase - 1)], change = (patch: Partial<Workspace>) => m.update(patch)
  const reviewCost = () => { const cost = v.costs.at(-1) ?? 0; m.update({ reserve: v.reserve + cost, costs: v.costs.slice(0, -1), passed: false }) }
  return <Frame {...m} {...v} phases={['Mission plan', ...mission.stages.map(stage => stage.title)]} resources={[`${mission.resource}: ${v.reserve}/18`, `Checks: ${v.checks}`, `Tips: ${v.hints}`]} ending={`${mission.ending} Saved ${v.reserve} from 18 units of stock. Passed with ${v.hints ? 'using hints' : 'independent choice of actions'}.`}>
    {v.phase === 0 ? <><Brief><p>{mission.hook}</p><p>The team has 18 reserve units. At each stage, consumption depends on the decision: every three activities or construction units started require one unit of supply. Failed checks do not consume it.</p></Brief><div className={s.missionPlan}>{mission.stages.map((stage, i) => <section key={stage.title}><small>{i + 1}. {mechanicNames[stage.kind]}</small><h3>{stage.title}</h3><p>{stage.brief}</p></section>)}</div><p>Before the last stage: {mission.incident} The event will take away 3 units of supply. Previous decisions can be revised with a refund of their cost.</p><Go onClick={() => m.update({ phase: 1, ...initialWorkspace(mission.stages[0]) })}>Start mission</Go></> : <>
      {v.phase === 3 && <aside className={s.incident}><strong>Change of situation −3 reserves</strong><p>{mission.incident}</p><small>Taken into account during the transition. The remainder depends on previous decisions.</small></aside>}
      <Brief><p>{activity.brief}</p></Brief>
      <fieldset className={s.activityControls} disabled={v.passed}><ActivityField activity={activity} work={v} change={change}/></fieldset>
      {!v.passed ? <div className={s.row}><Go onClick={() => { const result = evaluateActivity(activity, v, v.reserve); m.update({ checks: v.checks + 1 }); m.check(result, result.ok ? { passed: true, reserve: v.reserve - result.cost, costs: [...v.costs, result.cost] } : undefined) }}>Try the solution</Go><button onClick={() => m.update({ showHint: !v.showHint, hints: v.showHint ? v.hints : v.hints + 1 })}>{v.showHint ? 'Hide tooltip' : 'Discussion Prompt'}</button></div> : <div className={s.row}><Go onClick={() => {
        if (v.phase === 3) m.update({ done: true })
        else m.update({ phase: v.phase + 1, passed: false, reserve: v.reserve - (v.phase === 2 ? 3 : 0), showHint: false, ...initialWorkspace(mission.stages[v.phase]) })
      }}>{v.phase === 3 ? 'Complete the mission' : 'Apply the result and continue'}</Go><button onClick={reviewCost}>Improve this solution</button></div>}
      {v.showHint && <aside className={s.manual}><strong>Discuss strategy</strong><p>{hints[activity.kind]}</p><small>The tutor can ask questions, and the student performs the actions on the field.</small></aside>}
      {!v.passed && v.phase > 1 && <button className={s.back} onClick={() => m.update({ phase: v.phase - 1, reserve: v.reserve + (v.costs.at(-1) ?? 0) + (v.phase === 3 ? 3 : 0), costs: v.costs.slice(0,-1), ...initialWorkspace(mission.stages[v.phase - 2]), showHint: false })}>Review previous step</button>}
      <details className={s.notebook}><summary>What remains from previous decisions</summary>{v.costs.length ? v.costs.map((cost, i) => <p key={i}>{mission.stages[i].title}: completed, consumption {cost}.</p>) : <p>No results have been applied yet.</p>}<p>In stock {v.reserve}. {v.phase < 3 ? 'The event before the last stage will require 3 more.' : 'The cost of the event has already been taken into account.'}</p></details>
    </>}
  </Frame>
}
