import type { QuizQuestion } from '../quiz-rush'

type QuestionSeed = [prompt: string, options: [string, string, string], correctIndex: number, explanation: string]
function lesson(id: string, title: string, seeds: QuestionSeed[]) {
  return { id, title, questions: seeds.map(([prompt, options, correctIndex, explanation], index): QuizQuestion => ({
    id: `${id}-${index + 1}`, prompt, options, correctIndex, explanation,
  })) }
}

// Original short demonstration sets. Each campaign has ten distinct questions.
export const subjectLessons = [
  lesson('quiz-1', 'English', [
    ['The employee asks to show your passport. What to answer?', ['Here you are.', 'Never mind.', 'It is up to you.'], 0, 'Here you are said when an object or document is handed over.'],
    ['How to ask about the reason for a flight delay?', ['Where is my chair?', 'Why has the flight been delayed?', 'Can I close the gate?'], 1, 'Why has the flight been delayed? — Why was the flight delayed?'],
    ['What does carry-on luggage mean?', ['Hand luggage', 'Luggage strap', 'Boarding pass'], 0, 'Carry-on luggage - luggage that is taken into the cabin.'],
    ['Select form: She ___ English every day.', ['study', 'studying', 'studies'], 2, 'In the Present Simple, studies are used after she.'],
    ['Select form: We ___ a film yesterday.', ['watched', 'watch', 'have watch'], 0, 'Yesterday indicates a completed past: watched.'],
    ['Choose a preposition: I am interested ___ music.', ['at', 'in', 'on'], 1, 'Stable combination: interested in - to be interested in something.'],
    ['Choose the comparative form of the word good.', ['gooder', 'best', 'better'], 2, 'Good → better → best. Better - comparative degree.'],
    ['How to politely ask for a glass of water?', ['Could I have a glass of water, please?', 'Water must come.', 'You give water yesterday.'], 0, 'Could I have...please? - a natural polite request.'],
    ['Select form: There ___ some milk in the refrigerator.', ['are', 'is', 'be'], 1, 'Milk is an uncountable noun, so there is.'],
    ['Select the form: If it rains, we ___ at home.', ['stayed', 'would stayed', 'will stay'], 2, 'In the first conditional sentence: if + Present Simple, will + verb.'],
  ]),
  lesson('language-arts', 'Language Arts', [
    ['Which word is a noun?', ['Run', 'Joy', 'Quick'], 1, 'Joy names a feeling, so it is a noun.'],
    ['Which word is a verb?', ['Read', 'Book', 'Happy'], 0, 'Read describes an action.'],
    ['Choose the plural of child.', ['Childs', 'Childes', 'Children'], 2, 'Children is the irregular plural of child.'],
    ['Which spelling is correct?', ['Recieve', 'Receive', 'Receeve'], 1, 'The correct spelling is receive.'],
    ['Choose the contraction of do not.', ["Don't", 'Doesnt', 'Didnt'], 0, "Don't combines do and not; the apostrophe marks the missing letter."],
    ['Complete: She ___ to school daily.', ['walk', 'walking', 'walks'], 2, 'A third-person singular subject takes walks in the present simple.'],
    ['Find the subject: Birds sing in the morning.', ['Morning', 'Birds', 'Sing'], 1, 'Birds perform the action, so birds is the subject.'],
    ['Which word is a synonym of brave?', ['Courageous', 'Quiet', 'Weak'], 0, 'Courageous and brave have similar meanings.'],
    ['Which word is the opposite of tall?', ['Large', 'Long', 'Short'], 2, 'Tall and short are opposites when describing height.'],
    ['Complete: That bag belongs to Maya. It is ___ bag.', ['Maya', "Maya's", 'Mayas'], 1, "Maya's shows possession."],
  ]),
  lesson('quiz-2', 'Biology', [
    ['Where is most of the DNA in a eukaryotic cell located?', ['In the core', 'In vacuole', 'In the cell wall'], 0, 'Most of the DNA of a eukaryotic cell is found in the nucleus.'],
    ['Where does photosynthesis occur in plants?', ['In ribosomes', 'In chloroplasts', 'In the core'], 1, 'Chloroplasts contain chlorophyll and enable photosynthesis.'],
    ['What regulates the metabolism between the cell and the environment?', ['Chromosome', 'Nucleolus', 'Cell membrane'], 2, 'The membrane selectively allows substances to pass in and out of the cell.'],
    ['What cell structure synthesizes proteins?', ['Ribosome', 'Vacuole', 'Cell wall'], 0, 'Protein synthesis occurs on ribosomes.'],
    ['What cell structure is involved in obtaining energy during respiration?', ['Chloroplast', 'Mitochondria', 'Nucleolus'], 1, 'Mitochondria are involved in cellular respiration and ATP synthesis.'],
    ['Which plant organ usually absorbs water from the soil?', ['Flower', 'Fruit', 'Root'], 2, 'Water and minerals are supplied through the roots.'],
    ['What gas do plants produce during photosynthesis?', ['Oxygen', 'Nitrogen', 'Hydrogen'], 0, 'During photosynthesis, oxygen is released.'],
    ['What group does the frog belong to?', ['Reptiles', 'Amphibians', 'Mammals'], 1, 'Frogs are amphibians, or amphibians.'],
    ['What carries oxygen in human blood?', ['Platelets', 'Plasma without cells', 'Red blood cells'], 2, 'Hemoglobin in red blood cells binds and carries oxygen.'],
    ['Which organ system ensures the movement of blood?', ['Blood', 'Digestive', 'excretory'], 0, 'The heart and blood vessels make up the circulatory system.'],
  ]),
  lesson('world', 'Our World', [
    ['What comes after spring?', ['Autumn', 'Summer', 'Winter'], 1, 'After spring comes summer.'],
    ['What object helps determine the cardinal directions?', ['Compass', 'Thermometer', 'Libra'], 0, 'The compass needle helps determine the direction north.'],
    ['What does a thermometer measure?', ['Length', 'Mass', 'Temperature'], 2, 'The thermometer measures temperature.'],
    ['What is water in a solid state called?', ['Steam', 'Ice', 'Fog'], 1, 'The solid state of water is ice.'],
    ['Which animal is domestic?', ['Cow', 'Moose', 'Wolf'], 0, 'A cow is a domestic animal.'],
    ['What is the name of the star closest to Earth?', ['Moon', 'Mars', 'Sun'], 2, 'The Sun is the star of our planetary system.'],
    ['Which part of the plant produces seeds after pollination?', ['Root', 'Flower', 'stem'], 1, 'After pollination and fertilization, seeds form in the flower.'],
    ['What helps a bird fly?', ['Wings', 'Hooves', 'Fins'], 0, 'Birds use wings to fly.'],
    ['What is the name of the reduced image of the area from above?', ['Portrait', 'Still life', 'Site plan'], 2, 'The site plan shows a small area from above in a reduced view.'],
    ['What phenomenon is associated with the transition of water into steam?', ['Freezing', 'Evaporation', 'Melting'], 1, 'When liquid water evaporates, it turns into a gaseous state.'],
  ]),
  lesson('physics', 'Physics', [
    ['What SI units are used to measure force?', ['Newtons', 'Meters', 'Seconds'], 0, 'The SI unit of force is newton (N).'],
    ['How to calculate the speed of uniform motion?', ['s × t', 's ÷ t', 't ÷ s'], 1, 'Speed ​​is equal to the ratio of path to time: v = s/t.'],
    ['A body travels 100 m in 20 s. What\'s the speed?', ['20 m/s', '2 m/s', '5 m/s'], 2, '100 ÷ 20 = 5 m/s.'],
    ['What device measures force?', ['Dynamometer', 'Ammeter', 'Barometer'], 0, 'A dynamometer measures force by the deformation of an elastic element.'],
    ['In what SI units is electric current measured?', ['Volts', 'Amps', 'Ohms'], 1, 'Current is measured in amperes (A).'],
    ['What device measures voltage?', ['Thermometer', 'Ammeter', 'Voltmeter'], 2, 'A voltmeter measures the voltage between two points in a circuit.'],
    ['What attracts bodies to the Earth?', ['Gravity', 'Elastic force', 'Friction force'], 0, 'Gravity is related to the gravitational pull of the Earth.'],
    ['How to calculate the density of a substance?', ['m × V', 'm ÷ V', 'V ÷ m'], 1, 'Density is equal to the ratio of mass to volume: ρ = m/V.'],
    ['In what medium does sound not travel?', ['In the water', 'In the air', 'In a vacuum'], 2, 'Sound needs a material medium; It doesn\'t exist in a vacuum.'],
    ['What energy is associated with the movement of a body?', ['Kinetic', 'Chemical', 'Potential elasticity'], 0, 'Kinetic energy depends on the mass and speed of the body.'],
  ]),
  lesson('chemistry', 'Chemistry', [
    ['What is the name for the chemical element oxygen?', ['O', 'C', 'H'], 0, 'The symbol for oxygen is O.'],
    ['What is the formula of water?', ['CO₂', 'H₂O', 'O₂'], 1, 'A water molecule contains two hydrogen atoms and one oxygen atom.'],
    ['What does the symbol Na mean?', ['Nitrogen', 'Neon', 'Sodium'], 2, 'Na is the chemical symbol for sodium.'],
    ['What consists of atoms of one chemical element?', ['Simple substance', 'Mixture', 'Complex substance'], 0, 'A simple substance is formed by atoms of one element.'],
    ['What is a positively charged particle in an atomic nucleus called?', ['Electron', 'Proton', 'Neutron'], 1, 'A proton has a positive electrical charge.'],
    ['Which particle has a negative charge?', ['Neutron', 'Proton', 'Electron'], 2, 'The electron has a negative charge.'],
    ['What substance has the formula CO₂?', ['Carbon dioxide', 'Oxygen', 'Hydrogen'], 0, 'CO₂ is carbon dioxide, or carbon dioxide.'],
    ['What is a chemical transformation?', ['Ice melting', 'Rusting iron', 'Grinding salt'], 1, 'When rusting occurs, new substances are formed; it\'s a chemical change.'],
    ['What is the mixture?', ['Pure copper', 'Pure oxygen', 'Air'], 2, 'Air contains nitrogen, oxygen and other gases.'],
    ['What does the atomic number of an element show?', ['Number of protons', 'Number of molecules', 'Sample weight'], 0, 'The atomic number is equal to the number of protons in the nucleus.'],
  ]),
  lesson('geography', 'Geography', [
    ['Which ocean is the largest by area?', ['Quiet', 'Atlantic', 'Indian'], 0, 'The Pacific Ocean is the largest ocean on Earth.'],
    ['On which continent is the Sahara Desert located?', ['Eurasia', 'Africa', 'South America'], 1, 'The Sahara is located in northern Africa.'],
    ['Which line divides the Earth into the Northern and Southern Hemispheres?', ['Prime meridian', 'Northern Tropic', 'Equator'], 2, 'The equator has a latitude of 0° and separates the hemispheres.'],
    ['What does the map scale show?', ['The ratio of the distance on the map to the real one', 'Only the height of the mountains', 'Air temperature'], 0, 'The scale shows how many times the distances are reduced on the map.'],
    ['What does latitude measure?', ['Distance to the Moon', 'Angle from equator', 'Height above the sea'], 1, 'Latitude is the angular distance from the equator to the north or south.'],
    ['Where is Antarctica?', ['At the North Pole', 'At the equator', 'Around the South Pole'], 2, 'Antarctica is located in the south polar region.'],
    ['What is the place where the river begins?', ['Source', 'Estuary', 'Inflow'], 0, 'The source is the place where the river begins.'],
    ['What is the name of the place where the river flows?', ['watershed', 'Estuary', 'Source'], 1, 'The mouth is the place where a river flows into another body of water.'],
    ['What device measures atmospheric pressure?', ['Thermometer', 'Anemometer', 'Barometer'], 2, 'A barometer measures atmospheric pressure.'],
    ['What is the name of the shell of the Earth consisting of water?', ['Hydrosphere', 'Lithosphere', 'Atmosphere'], 0, 'The hydrosphere includes the oceans, rivers, lakes, ice and other waters of the Earth.'],
  ]),
  lesson('history', 'History', [
    ['Which city was the center of Ancient Rome?', ['Rome', 'Athens', 'Babylon'], 0, 'Ancient Rome was named after the city of Rome.'],
    ['What is the name of the ancient Egyptian writing system?', ['Cyrillic', 'Hieroglyphs', 'Latin'], 1, 'Ancient Egypt used hieroglyphic writing.'],
    ['In what century was St. Petersburg founded (1703)?', ['XVI', 'XVII', 'XVIII'], 2, 'The year 1703 dates back to the 18th century.'],
    ['What century does 1242 include?', ['XIII', 'XII', 'XIV'], 0, 'The years 1201–1300 belong to the 13th century.'],
    ['Who was the first man to fly into space?', ['Alexey Leonov', 'Yuri Gagarin', 'Neil Armstrong'], 1, 'Yuri Gagarin made the first manned space flight on April 12, 1961.'],
    ['Where did the ancient Olympic Games originate?', ['In Egypt', 'In China', 'In Greece'], 2, 'The ancient Olympic Games were held in Olympia, Greece.'],
    ['What do you call a scientist who studies the past through excavations?', ['Archaeologist', 'Astronomer', 'Geologist'], 0, 'An archaeologist studies material traces of the past.'],
    ['Which source is written?', ['Stone ax', 'Chronicle', 'Clay vessel without inscriptions'], 1, 'The chronicle contains written records of events.'],
    ['Who is associated with the advent of European movable type printing?', ['Galileo Galilei', 'Isaac Newton', 'Johannes Gutenberg'], 2, 'Johannes Gutenberg developed the printing system in Europe in the 15th century.'],
    ['How many years are there in one century?', ['100', '10', '1000'], 0, 'A century is a period of 100 years.'],
  ]),
  lesson('informatics', 'Computer Science', [
    ['What digits are used in the binary system?', ['0 and 1', '1 and 2', '0 to 9'], 0, 'The binary system uses two digits: 0 and 1.'],
    ['How many bits are in one byte?', ['4', '8', '16'], 1, 'One byte consists of eight bits.'],
    ['What is an algorithm?', ['Any picture', 'Random set of words', 'Sequence of steps to solve the problem'], 2, 'The algorithm specifies the order of actions to solve a problem.'],
    ['What device enters text?', ['Keyboard', 'Printer', 'Monitor'], 0, 'The keyboard is used to enter text and commands.'],
    ['Which device outputs the image?', ['Microphone', 'Monitor', 'Scanner'], 1, 'The monitor shows the image generated by the computer.'],
    ['What is the name for repeating actions in a program?', ['Branching', 'Assignment', 'Cycle'], 2, 'The loop performs the actions repeatedly.'],
    ['What does a conditional statement do?', ['Selects an action based on a condition', 'Always turns off the computer', 'Only outputs music'], 0, 'A conditional statement creates a branch depending on whether a condition is tested.'],
    ['What is the binary number 10 in decimal system?', ['10', '2', '1'], 1, '10₂ = 1 × 2 + 0 = 2₁₀.'],
    ['What sign often represents assignment in programming?', ['?', '#', '='], 2, 'In many languages, the = sign assigns a value to a variable.'],
    ['What is a variable in a program?', ['Name for the stored value', 'Monitor type', 'Keyboard key'], 0, 'A variable allows you to store a value and access it by name.'],
  ]),
  lesson('literature', 'Literature', [
    ['Who wrote "The Tale of the Fisherman and the Fish"?', ['A. S. Pushkin', 'N.V. Gogol', 'I. A. Krylov'], 0, 'The author of “The Tale of the Fisherman and the Fish” is Alexander Pushkin.'],
    ['Who wrote the fable "The Crow and the Fox"?', ['M. Yu. Lermontov', 'I. A. Krylov', 'A. P. Chekhov'], 1, 'This fable was written by Ivan Krylov.'],
    ['What is the name of a short educational story, often with animals?', ['Roman', 'Oda', 'fable'], 2, 'A fable usually contains a moral conclusion - a moral.'],
    ['What is rhyme?', ['Consonance of the ends of poetic lines', 'Description of the hero', 'Chapter title'], 0, 'Rhyme connects lines by consonance of their endings.'],
    ['What technique was used: “White birch - as if in silver”?', ['Hyperbole', 'Comparison', 'Dialogue'], 1, 'The word "as if" indicates a comparison.'],
    ['What technique was used: “The wind whispers”?', ['Antithesis', 'Transfer', 'Personification'], 2, 'Human action is attributed to an inanimate phenomenon.'],
    ['What do you call a conversation between two characters?', ['Dialogue', 'Landscape', 'Epithet'], 0, 'Dialogue is a conversation between two or more characters.'],
    ['What is the landscape in the work?', ['Description of clothing', 'Description of nature', 'List of chapters'], 1, 'The landscape depicts nature and the surrounding area.'],
    ['Who wrote the story "Kashtanka"?', ['L. N. Tolstoy', 'A. S. Pushkin', 'A. P. Chekhov'], 2, 'The author of “Kashtanka” is Anton Chekhov.'],
    ['What is the artistic definition called, for example, “golden autumn”?', ['Epithet', 'Rhyme', 'Dialogue'], 0, 'An epithet figuratively characterizes an object or phenomenon.'],
  ]),
  lesson('social', 'Social Studies', [
    ['What do you call a group of people connected by common goals and activities?', ['Social group', 'Mainland', 'Constellation'], 0, 'A social group unites people according to a significant social characteristic.'],
    ['What is material culture?', ['Moral Rule', 'building', 'Mathematical idea'], 1, 'Buildings are objects of material culture.'],
    ['What is an example of spiritual culture?', ['Bridge', 'Tool', 'Musical piece'], 2, 'A piece of music belongs to spiritual culture.'],
    ['What is the exchange of goods for money called?', ['Purchase and sale', 'Evaporation', 'Photosynthesis'], 0, 'Purchase and sale involves the transfer of goods for a monetary payment.'],
    ['What is a need?', ['Unit of length', 'Need something', 'Type of transport'], 1, 'Need is a person’s need for something necessary.'],
    ['What are biological needs?', ['Recognition', 'Communication', 'Food'], 2, 'Food is necessary to maintain the life of the body.'],
    ['What is it called knowing the world through observations and evidence?', ['Science', 'Advertising', 'Fashion'], 0, 'Science seeks to obtain and test knowledge about the world.'],
    ['What helps to resolve disagreements peacefully?', ['Threat', 'Dialogue', 'Insult'], 1, 'Dialogue allows you to clarify positions and find a solution.'],
    ['What is the ability to evaluate one\'s own actions called?', ['Speed', 'Weight', 'Self-esteem'], 2, 'Self-esteem is associated with evaluating one\'s own qualities and actions.'],
    ['What is an example of cooperation?', ['Working together on a project', 'Refusal to listen to each other', 'Competition without common actions'], 0, 'Collaboration is joint activity for a common goal.'],
  ]),
]
