export type ContentFact = {
  left: string
  right: string
  explanation: string
}

export type ContentFactBank = {
  id: string
  title: string
  subject: string
  grade: string
  tags: string[]
  facts: ContentFact[]
}

function fact(left: string, right: string, explanation: string): ContentFact {
  return { left, right, explanation }
}

export const contentFactBanks: ContentFactBank[] = [
  {
    id: 'preschool-shapes',
    title: 'Figures and signs',
    subject: 'Preschool development',
    grade: '5–7 years',
    tags: ['preschool development', 'figures', 'logic'],
    facts: [
      fact('Circle', 'No corners', 'The circle\'s border does not contain corners.'),
      fact('Triangle', 'Three sides', 'A triangle has three sides and three angles.'),
      fact('Square', 'Four equal sides', 'All four sides of the square are equal.'),
      fact('Rectangle', 'Opposite sides are equal', 'A rectangle has equal pairs of opposite sides.'),
      fact('Oval', 'Elongated round shape', 'The oval looks like an elongated circle.'),
      fact('Pentagon', 'Five sides', 'The name of the figure refers to the five sides.'),
      fact('Hexagon', 'Six sides', 'A hexagon has six sides.'),
      fact('Diamond', 'Four equal sides without obligatory right angles', 'A rhombus has all sides equal, but the angles do not have to be right.'),
    ],
  },
  {
    id: 'primary-measures',
    title: 'Units and ratios',
    subject: 'Primary School',
    grade: '2–4 grade',
    tags: ['primary school', 'units of measurement', 'mathematics'],
    facts: [
      fact('1 meter', '100 centimeters', 'There are one hundred centimeters in one meter.'),
      fact('1 kilometer', '1000 meters', 'There are a thousand meters in one kilometer.'),
      fact('1 kilogram', '1000 grams', 'There are a thousand grams in one kilogram.'),
      fact('1 hour', '60 minutes', 'One hour contains sixty minutes.'),
      fact('1 minute', '60 seconds', 'One minute contains sixty seconds.'),
      fact('1 day', '24 hours', 'A day consists of twenty-four hours.'),
      fact('1 week', '7 days', 'There are seven days in a week.'),
      fact('1 decade', '10 years', 'A decade is a period of ten years.'),
    ],
  },
  {
    id: 'language-arts-parts-of-speech',
    title: 'Parts of speech',
    subject: 'Language Arts',
    grade: '4–7 grade',
    tags: ['language arts', 'parts of speech', 'grammar'],
    facts: [
      fact('Noun', 'Object or phenomenon', 'A noun names an object, person or phenomenon.'),
      fact('Verb', 'Action or state', 'A verb denotes an action or state.'),
      fact('Adjective', 'Item attribute', 'An adjective names a characteristic of an object.'),
      fact('Adverb', 'Sign of action', 'An adverb often explains a verb and denotes a sign of action.'),
      fact('Pronoun', 'Points but does not name', 'A pronoun indicates an object, attribute or quantity.'),
      fact('Numeral', 'Quantity or order', 'A numeral denotes number, quantity, or order when counting.'),
      fact('Preposition', 'Links words in a phrase', 'A preposition expresses the dependence of one word on another.'),
      fact('Conjunction', 'Connects homogeneous members and parts of a sentence', 'A conjunction serves to connect words and parts of a complex sentence.'),
    ],
  },
  {
    id: 'literature-devices',
    title: 'Means of expression',
    subject: 'Literature',
    grade: '5–9 grade',
    tags: ['literature', 'trails', 'expressiveness'],
    facts: [
      fact('Metaphor', 'Hidden comparison', 'A metaphor transfers the properties of one phenomenon to another without words of comparison.'),
      fact('Epithet', 'Figurative definition', 'An epithet creates an expressive feature of an object or phenomenon.'),
      fact('Personification', 'Properties of man and non-living things', 'Personification imparts human qualities to inanimate things.'),
      fact('Hyperbole', 'Artistic exaggeration', 'Hyperbole intentionally enhances the scale of a feature.'),
      fact('Comparison', 'Comparison through a common feature', 'Comparison brings two images closer together based on a selected attribute.'),
      fact('Antithesis', 'Sharp contrast', 'Antithesis is built on the contrast of images or concepts.'),
      fact('Allegory', 'Allegorical image of an idea', 'An allegory conveys an abstract idea through a concrete image.'),
      fact('Anaphora', 'Repeat at the beginning of lines or phrases', 'Anaphora repeats one element at the beginning of adjacent segments of speech.'),
    ],
  },
  {
    id: 'english-travel', title: 'Travel English', subject: 'English', grade: 'A2–B1',
    tags: ['English', 'travel', 'adults'],
    facts: [
      fact('departure', 'The act of leaving', 'A departure board shows when transport leaves.'),
      fact('arrival', 'Reaching your destination', 'The arrivals hall is where arriving passengers meet people.'),
      fact('receipt', 'A document proving payment', 'Keep your receipt as proof that you paid.'),
      fact('appointment', 'An arranged meeting', 'An appointment has an agreed time and purpose.'),
      fact('luggage', 'Bags taken on a journey', 'Luggage is an uncountable noun.'),
      fact('boarding pass', 'A document used to board a flight', 'Show your boarding pass at the gate.'),
      fact('reservation', 'A place or service booked in advance', 'A hotel reservation holds a room for you.'),
      fact('delay', 'An event happening later than planned', 'A delayed flight leaves later than scheduled.'),
    ],
  },
  {
    id: 'german-travel',
    title: 'German on a trip',
    subject: 'German language',
    grade: 'A1–A2',
    tags: ['German', 'travel', 'phrases'],
    facts: [
      fact('Guten Morgen', 'Good morning', 'This is how people say hello in the morning.'),
      fact('Danke', 'Thank you', 'Danke expresses gratitude.'),
      fact('Bitte', 'Please', 'Bitte is used in request and in response to gratitude.'),
      fact('Entschuldigung', 'Sorry', 'Entschuldigung helps to politely apologize or address.'),
      fact('Bahnhof', 'Station', 'Bahnhof is a railway station or train station.'),
      fact('Fahrkarte', 'Ticket', 'Fahrkarte - transport ticket.'),
      fact('Rechnung', 'Account', 'Rechnung - invoice for payment.'),
      fact('Termin', 'Appointment', 'Term—the agreed upon time of meeting or reception.'),
    ],
  },
  {
    id: 'french-basics',
    title: 'French phrases',
    subject: 'French language',
    grade: 'A1–A2',
    tags: ['French', 'phrases', 'communication'],
    facts: [
      fact('bonjour', 'hello', 'Bonjour is a neutral daytime greeting.'),
      fact('merci', 'thank you', 'Merci expresses gratitude.'),
      fact('s’il vous plaît', 'please', 'The phrase makes the request polite.'),
      fact('au revoir', 'goodbye', 'Au revoir is used when saying goodbye.'),
      fact('excusez-moi', 'sorry', 'Excusez-moi is used to apologize or attract attention.'),
      fact('la gare', 'station', 'La gare - train station.'),
      fact('le billet', 'ticket', 'Le billet is a ticket for transport or an event.'),
      fact('l’addition', 'restaurant bill', 'L\'addition is asked after eating in a cafe or restaurant.'),
    ],
  },
  {
    id: 'spanish-basics',
    title: 'Spanish phrases',
    subject: 'Spanish language',
    grade: 'A1–A2',
    tags: ['Spanish', 'phrases', 'communication'],
    facts: [
      fact('hola', 'hi', 'Hola is a universal informal greeting.'),
      fact('gracias', 'thank you', 'Gracias expresses gratitude.'),
      fact('por favor', 'please', 'Por favor makes a request polite.'),
      fact('hasta luego', 'see you soon', 'Hasta luego is used when saying goodbye.'),
      fact('perdón', 'sorry', 'Perdón is used for a short apology.'),
      fact('la estación', 'station', 'La estación - station or train station.'),
      fact('el billete', 'ticket', 'El billete - transport ticket.'),
      fact('la cuenta', 'account', 'La cuenta - invoice to be paid.'),
    ],
  },
  {
    id: 'chinese-basics',
    title: 'Chinese phrases',
    subject: 'Chinese language',
    grade: 'Entry level',
    tags: ['Chinese', 'pinyin', 'communication'],
    facts: [
      fact('你好', 'nǐ hǎo - hello', '你好 is a basic greeting.'),
      fact('谢谢', 'xièxie - thank you', '谢谢 expresses gratitude.'),
      fact('再见', 'zàijiàn - goodbye', '再见 is used when saying goodbye.'),
      fact('请', 'qǐng - please', '请 is used in a polite request or invitation.'),
      fact('对不起', 'duìbuqǐ - sorry', '对不起 expresses an apology.'),
      fact('车站', 'chēzhan - station', '车站 denotes a transport station.'),
      fact('票', 'piào - ticket', '票 stands for ticket.'),
      fact('多少钱', 'duōshao qián - how much does it cost?', '多少钱 is used to ask the price.'),
    ],
  },
  {
    id: 'arithmetic-fractions',
    title: 'Fractions and decimal notation',
    subject: 'Arithmetic',
    grade: '5th–6th grade',
    tags: ['arithmetic', 'fractions', 'decimals'],
    facts: [
      fact('1/2', '0,5', 'One second is equal to five tenths.'),
      fact('1/4', '0,25', 'One quarter is equal to twenty-five hundredths.'),
      fact('3/4', '0,75', 'Three quarters is equal to seventy-five hundredths.'),
      fact('1/5', '0,2', 'One fifth is equal to two tenths.'),
      fact('2/5', '0,4', 'Two fifths is equal to four tenths.'),
      fact('3/5', '0,6', 'Three fifths is equal to six tenths.'),
      fact('4/5', '0,8', 'Four fifths is equal to eight tenths.'),
      fact('1/8', '0,125', 'One eighth is equal to one hundred twenty-five thousandths.'),
    ],
  },
  {
    id: 'algebra-identities',
    title: 'Algebraic identities',
    subject: 'Algebra',
    grade: '7–9 grade',
    tags: ['algebra', 'identity', 'formulas'],
    facts: [
      fact('(a + b)²', 'a² + 2ab + b²', 'The square of the sum contains twice the product.'),
      fact('(a − b)²', 'a² − 2ab + b²', 'The square of the difference contains negative twice the product.'),
      fact('a² − b²', '(a − b)(a + b)', 'The difference of squares is decomposed into the product of the sum and the difference.'),
      fact('a(b + c)', 'ab + ac', 'The factor before the parenthesis is multiplied by each term.'),
      fact('(a + b)³', 'a³ + 3a²b + 3ab² + b³', 'The coefficients of the sum cube are 1, 3, 3, 1.'),
      fact('(a − b)³', 'a³ − 3a²b + 3ab² − b³', 'In the difference cube, the signs alternate.'),
      fact('a³ + b³', '(a + b)(a² − ab + b²)', 'The sum of the cubes contains the sum in the first factor.'),
      fact('a³ − b³', '(a − b)(a² + ab + b²)', 'The difference of cubes contains the difference in the first factor.'),
    ],
  },
  {
    id: 'geometry-formulas',
    title: 'Geometric formulas',
    subject: 'Geometry',
    grade: '7–10 grade',
    tags: ['geometry', 'formulas', 'area', 'volume'],
    facts: [
      fact('Area of a triangle', 'S = a · h / 2', 'The area is equal to half the product of the base and the height.'),
      fact('Area of a rectangle', 'S = a · b', 'Multiply the lengths of adjacent sides.'),
      fact('Area of a circle', 'S = πr²', 'The area of a circle depends on the square of the radius.'),
      fact('Pythagorean theorem', 'c² = a² + b²', 'For a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.'),
      fact('Circumference', 'L = 2πr', 'The circumference of a circle is equal to twice the product of π and the radius.'),
      fact('Area of a parallelogram', 'S = a · h', 'The base is multiplied by the height drawn to it.'),
      fact('Area of trapezoid', 'S = (a + b) · h / 2', 'Half the sum of the bases is multiplied by the height.'),
      fact('Volume of a straight prism', 'V = Smain h', 'The area of the base is multiplied by the height of the prism.'),
    ],
  },
  {
    id: 'probability-statistics',
    title: 'Probability and Statistics',
    subject: 'Probability and Statistics',
    grade: '7–10 grade',
    tags: ['probability', 'statistics', 'data'],
    facts: [
      fact('P = 0', 'Impossible event', 'An impossible event has a probability of zero.'),
      fact('P = 1', 'Reliable event', 'A certain event has a probability of one.'),
      fact('P = 0,5', 'Equal chances', 'One-half probability corresponds to equal chances.'),
      fact('P(A) + P(not A)', '1', 'The event and its add-on cover all outcomes.'),
      fact('Arithmetic mean', 'Sum of values divided by their number', 'The average takes into account each value in the set.'),
      fact('Median', 'Central value of ordered series', 'The median divides the ordered series in half.'),
      fact('Fashion', 'Most common meaning', 'Fashion appears in the set more often than others.'),
      fact('Scope', 'Maximum minus minimum', 'The span shows the width of the set of values.'),
    ],
  },
  {
    id: 'calculus-derivatives',
    title: 'Basic derivatives',
    subject: 'Mathematical analysis',
    grade: '10–11 grade, university',
    tags: ['mathematical analysis', 'derivative', 'functions'],
    facts: [
      fact('xⁿ', 'n · xⁿ⁻¹', 'The exponent becomes a multiplier and decreases by one.'),
      fact('sin x', 'cos x', 'The derivative of the sine is equal to the cosine.'),
      fact('cos x', '−sin x', 'The derivative of the cosine is equal to minus sine.'),
      fact('eˣ', 'eˣ', 'An exponent with base e is the same as its derivative.'),
      fact('ln x', '1/x', 'The derivative of the natural logarithm is equal to one divided by x.'),
      fact('Constant C', '0', 'A constant quantity does not change, so its derivative is zero.'),
      fact('1/x', '−1/x²', 'Think of the function as x to the power minus one.'),
      fact('√x', '1/(2√x)', 'The root is represented as x to the power of one-half.'),
    ],
  },
  {
    id: 'informatics-core',
    title: 'Fundamentals of Computer Science',
    subject: 'Computer Science',
    grade: '5–9 grade',
    tags: ['computer science', 'algorithms', 'programming'],
    facts: [
      fact('Bit', 'Value 0 or 1', 'A bit is the smallest binary unit of information.'),
      fact('Byte', 'Eight bits', 'One byte consists of eight bits.'),
      fact('Algorithm', 'Final sequence of commands', 'The algorithm specifies the order of actions to solve a problem.'),
      fact('Variable', 'Named place for value', 'A variable allows you to store and change data.'),
      fact('Cycle', 'Repeating commands', 'The loop executes a block of commands several times.'),
      fact('Condition', 'Selecting an execution branch', 'The condition determines which set of commands to execute.'),
      fact('Function', 'Named reusable block', 'The function combines commands to be called again.'),
      fact('Array', 'Ordered set of elements', 'An array stores multiple elements with positional access.'),
    ],
  },
  {
    id: 'physics-units',
    title: 'Physical quantities and SI',
    subject: 'Physics',
    grade: '7–10 grade',
    tags: ['physics', 'SI', 'units of measurement'],
    facts: [
      fact('Strength', 'newton', 'The SI unit of force is newton.'),
      fact('Energy', 'joule', 'Energy and work are measured in joules.'),
      fact('Power', 'watt', 'Power is measured in watts.'),
      fact('Speed', 'meter per second', 'The basic SI unit of speed is meters per second.'),
      fact('Pressure', 'pascal', 'Pressure is measured in pascals.'),
      fact('Electric charge', 'pendant', 'The unit of electric charge is the coulomb.'),
      fact('Voltage', 'volt', 'Electrical voltage is measured in volts.'),
      fact('Resistance', 'ohm', 'Electrical resistance is measured in ohms.'),
    ],
  },
  {
    id: 'chemistry-elements',
    title: 'Elements and symbols',
    subject: 'Chemistry',
    grade: '7–9 grade',
    tags: ['chemistry', 'elements', 'symbols'],
    facts: [
      fact('Oxygen', 'O', 'The chemical symbol for oxygen is O.'),
      fact('Hydrogen', 'H', 'The chemical symbol for hydrogen is H.'),
      fact('Iron', 'Fe', 'The symbol Fe comes from the Latin ferrum.'),
      fact('Sodium', 'Na', 'The symbol Na comes from the Latin natrium.'),
      fact('Carbon', 'C', 'The chemical symbol for carbon is C.'),
      fact('Nitrogen', 'N', 'The chemical symbol for nitrogen is N.'),
      fact('Chlorine', 'Cl', 'The chemical symbol for chlorine is Cl.'),
      fact('Copper', 'Cu', 'The symbol Cu comes from the Latin cuprum.'),
    ],
  },
  {
    id: 'biology-cell',
    title: 'Cell and organelles',
    subject: 'Biology',
    grade: '6–9 grade',
    tags: ['biology', 'cell', 'organoids'],
    facts: [
      fact('Core', 'Storage of hereditary information', 'The nucleus of a eukaryotic cell contains the bulk of DNA.'),
      fact('Mitochondria', 'Cellular respiration and ATP synthesis', 'Mitochondria are involved in obtaining energy available to the cell.'),
      fact('Ribosome', 'Protein synthesis', 'On ribosomes, amino acids are combined to form proteins.'),
      fact('Cell membrane', 'Selective transport of substances', 'The membrane regulates the exchange of cells with the environment.'),
      fact('Cytoplasm', 'Organelle and Reaction Media', 'Organelles are located in the cytoplasm and many reactions take place.'),
      fact('Chloroplast', 'Photosynthesis', 'Photosynthesis occurs in the chloroplasts of a plant cell.'),
      fact('Plant vacuole', 'Supply of substances and maintenance of turgor', 'The large vacuole contains cell sap and maintains pressure.'),
      fact('Golgi apparatus', 'Modification and packaging of substances', 'The Golgi apparatus sorts and packages cellular products.'),
    ],
  },
  {
    id: 'ecology-system',
    title: 'Ecosystem and food connections',
    subject: 'Ecology',
    grade: '6–9 grade',
    tags: ['ecology', 'ecosystem', 'food chain'],
    facts: [
      fact('Producer', 'Creates organic matter', 'Producers synthesize organic substances from inorganic ones.'),
      fact('Consumer of the first order', 'Feeds on producers', 'This group often includes herbivores.'),
      fact('Second-order consumer', 'Feeds on primary consumers', 'This is the next level of the food chain.'),
      fact('Decomposer', 'Decomposes organic residues', 'Reducers return substances to the cycle.'),
      fact('Population', 'Individuals of the same species in a common area', 'Individuals of a population interact and reproduce for a long time.'),
      fact('Ecosystem', 'Community of organisms and environment', 'An ecosystem includes living organisms and nonliving components.'),
      fact('Habitat', 'Living conditions of the organism', 'The environment provides the body with resources and influences it.'),
      fact('Biodiversity', 'Variety of living forms', 'The concept includes diversity of genes, species and ecosystems.'),
    ],
  },
  {
    id: 'astronomy-planets',
    title: 'Planets of the Solar System',
    subject: 'Astronomy',
    grade: '5–10 grade',
    tags: ['astronomy', 'planets', 'solar system'],
    facts: [
      fact('Mercury', 'Closest planet to the Sun', 'Mercury\'s orbit is closest to the Sun than other planets.'),
      fact('Venus', 'Hottest planet', 'The dense atmosphere of Venus creates a strong greenhouse effect.'),
      fact('Earth', 'Liquid water on the surface', 'There are stable oceans of liquid water on Earth.'),
      fact('Mars', 'Volcano Olympus', 'Mars is home to the largest known volcano in the solar system.'),
      fact('Jupiter', 'The largest planet', 'Jupiter surpasses other planets in size and mass.'),
      fact('Saturn', 'Pronounced ring system', 'Saturn\'s rings are especially noticeable when observed.'),
      fact('Uranus', 'Strongly tilted axis of rotation', 'Uranus rotates as if lying on its side relative to its orbit.'),
      fact('Neptune', 'The most distant planet', 'Neptune is the most distant of the eight planets from the Sun.'),
    ],
  },
  {
    id: 'geography-map',
    title: 'Map and geographic lines',
    subject: 'Geography',
    grade: '5th–8th grade',
    tags: ['geography', 'map', 'coordinates'],
    facts: [
      fact('Equator', '0° latitude', 'The equator divides the Earth into the Northern and Southern Hemispheres.'),
      fact('Prime Meridian', '0° longitude', 'Geographical longitude is measured from the prime meridian.'),
      fact('Latitude', 'Angular distance from the equator', 'Latitude is measured north or south of the equator.'),
      fact('Longitude', 'Angular distance from prime meridian', 'Longitude is measured towards the east or west.'),
      fact('Isobar', 'Equal pressure line', 'Isobars connect points with equal atmospheric pressure.'),
      fact('Horizontal', 'Line of equal height', 'Contour lines show the relief on the map.'),
      fact('Scale', 'The relationship between the distance on the map and the terrain', 'The scale helps translate map lengths into real distances.'),
      fact('Map legend', 'Explanation of conventions', 'The legend reveals the meaning of colors, lines and icons.'),
    ],
  },
  {
    id: 'history-landmarks',
    title: 'Key historical dates',
    subject: 'History',
    grade: '6–10 grade',
    tags: ['history', 'dates', 'chronology'],
    facts: [
      fact('Fall of the Western Roman Empire', '476', 'The year 476 is traditionally considered the end of the history of the Western Roman Empire.'),
      fact('Columbus\'s first voyage to America', '1492', 'Columbus\'s expedition reached the Caribbean islands in 1492.'),
      fact('Beginning of the Reformation', '1517', 'The publication of Martin Luther\'s theses dates back to 1517.'),
      fact('US Declaration of Independence', '1776', 'The Declaration was adopted on July 4, 1776.'),
      fact('Beginning of the French Revolution', '1789', 'The storming of the Bastille took place in July 1789.'),
      fact('Abolition of serfdom in Russia', '1861', 'The Manifesto for the Emancipation of the Peasants was published in 1861.'),
      fact('Beginning of the First World War', '1914', 'The First World War began in the summer of 1914.'),
      fact('End of World War II', '1945', 'The Second World War ended in 1945.'),
    ],
  },
  {
    id: 'social-studies-core',
    title: 'Society and social institutions',
    subject: 'Social Studies',
    grade: '6–10 grade',
    tags: ['social studies', 'society', 'institutions'],
    facts: [
      fact('Family', 'Primary socialization', 'In the family, a person receives his first social skills and norms.'),
      fact('State', 'Public power', 'The state organizes public authority in a certain territory.'),
      fact('Education', 'Transfer of knowledge and culture', 'Education provides systematic training and socialization.'),
      fact('Market', 'Exchange of goods and services', 'Sellers and buyers interact in the market.'),
      fact('Social norm', 'Rule of conduct', 'Social norms regulate the expected behavior of people.'),
      fact('Social status', 'Position of a person in society', 'Status is associated with rights, responsibilities and expectations.'),
      fact('Social role', 'Expected behavior of a status holder', 'A role describes how a person acts in a certain position.'),
      fact('Culture', 'Values, norms and symbols', 'Culture preserves and transmits methods of human activity.'),
    ],
  },
  {
    id: 'economics-core',
    title: 'Economic concepts',
    subject: 'Economics',
    grade: '8–11 grade, adults',
    tags: ['economics', 'financial literacy', 'terms'],
    facts: [
      fact('Demand', 'Desire and ability to buy', 'Demand reflects the quantity of a product that buyers are willing to purchase.'),
      fact('Offer', 'Products that are ready to sell', 'Supply shows the volume of goods that sellers are willing to bring to the market.'),
      fact('Inflation', 'Sustained growth in the general price level', 'Inflation reduces the purchasing power of money.'),
      fact('Budget', 'Income and Expense Plan', 'A budget helps you compare income and expenses.'),
      fact('Revenue', 'All proceeds from sales', 'Revenue is calculated before deducting costs.'),
      fact('Costs', 'Production and labor costs', 'Costs include the resources needed for an activity.'),
      fact('Profit', 'Revenue minus costs', 'Profit shows the financial result after taking into account costs.'),
      fact('Competition', 'Rivalry between market participants', 'Competition arises for customers and resources.'),
    ],
  },
  {
    id: 'law-branches',
    title: 'Branches of law',
    subject: 'Right',
    grade: '8–11 grade',
    tags: ['right', 'branches of law', 'social studies'],
    facts: [
      fact('Civil law', 'Property and personal non-property relations', 'Civil law regulates the relations of legally equal participants.'),
      fact('Labor law', 'Employee-employer relations', 'Labor law regulates the conclusion and execution of employment relationships.'),
      fact('Family law', 'Marriage and family relations', 'Family law deals with marriage, parenthood and family responsibilities.'),
      fact('Criminal law', 'Crimes and Punishments', 'Criminal law defines criminal acts and penalties.'),
      fact('Constitutional law', 'Fundamentals of the state structure', 'This industry consolidates the foundations of the power and legal status of the individual.'),
      fact('Administrative law', 'Relations in the field of public administration', 'Administrative law regulates the activities of the executive branch and management.'),
      fact('Tax law', 'Establishment and payment of taxes', 'Tax law regulates mandatory payments of a public nature.'),
      fact('Procedural law', 'Procedure for consideration of legal cases', 'Procedural rules determine the procedures for protecting and applying the law.'),
    ],
  },
  {
    id: 'art-techniques',
    title: 'Art and technology',
    subject: 'fine arts',
    grade: '5th–9th grade, adults',
    tags: ['art', 'ISO', 'technology'],
    facts: [
      fact('Watercolor', 'Water based paint', 'Watercolor usually creates transparent layers of color.'),
      fact('Engraving', 'Impression from processed form', 'The image is transferred to paper from the printing plate.'),
      fact('sculpture', 'Volumetric art form', 'The sculpture is perceived in three dimensions.'),
      fact('Collage', 'Composition of connected fragments', 'A collage combines different materials and images.'),
      fact('Fresco', 'Painting on wet plaster', 'The fresco pigment is fixed together with the plaster.'),
      fact('Mosaic', 'Image from separate pieces', 'Mosaics are made from stone, glass or other elements.'),
      fact('Portrait', 'Image of a person', 'A portrait conveys the appearance and often the character of the model.'),
      fact('Landscape', 'Depiction of nature or locality', 'The main subject of the landscape becomes the space of the surrounding world.'),
    ],
  },
  {
    id: 'music-terms',
    title: 'Musical notations',
    subject: 'Music',
    grade: '5th–9th grade, adults',
    tags: ['music', 'tempo', 'dynamics'],
    facts: [
      fact('Allegro', 'Fast', 'Allegro denotes a fast, lively tempo.'),
      fact('Adagio', 'Slowly', 'Adagio denotes a slow tempo.'),
      fact('Crescendo', 'Gradually louder', 'Crescendo requires you to gradually increase the sound.'),
      fact('Diminuendo', 'Gradually quieter', 'Diminuendo requires you to gradually weaken the sound.'),
      fact('Forte', 'Loud', 'Forte denotes loud performance.'),
      fact('Piano', 'Quiet', 'Piano denotes quiet performance.'),
      fact('Legato', 'Connected', 'With legato, the sounds blend together smoothly.'),
      fact('Staccato', 'Jerky', 'With staccato, the sounds are performed briefly and separately.'),
    ],
  },
  {
    id: 'professional-communication',
    title: 'Work communication',
    subject: 'Professional courses',
    grade: 'Adults',
    tags: ['professional courses', 'communication', 'adults'],
    facts: [
      fact('Deadline', 'Latest time a task must be finished', 'The deadline fixes the moment by which the work must be ready.'),
      fact('Agenda', 'List of meeting topics', 'An agenda helps set the goals of the discussion in advance.'),
      fact('Feedback', 'Comments that help improve work', 'Useful feedback describes an observation and possible improvement.'),
      fact('Stakeholder', 'Person or group affected by a project', 'The stakeholder influences the project or depends on its outcome.'),
      fact('Brief', 'Brief description of the task and requirements', 'The brief agrees on the purpose, audience, constraints and outcome.'),
      fact('Iteration', 'Repeated improvement cycle', 'Iteration allows you to refine the solution in small steps.'),
      fact('Priority', 'Relative importance of task', 'Priority helps allocate limited resources.'),
      fact('Facilitation', 'Organizing a productive discussion', 'The facilitator helps the group move towards results.'),
    ],
  },
]
