import { mission as m, pack as p, sequence as q, sort as s, plot as g, schedule as t, transform as x, proof as d, route as r } from './builders'

export const englishMissions = [
  m('eng-hotel','The late check-in','English','A2–B1','Guest arrives late: make a request, check confirmation and plan counter actions.','The administrator works alone; key is issued only after checking the reservation.',[
    q('Ask for late arrival','Make a polite request for late check-in.',['Could I','check in','after ten','tonight?']),
    d('Booking conditions','The booking includes late check-in and a quiet room.',['Late check-in accepted','Quiet room confirmed'],[['Reception email','You may arrive after ten. We will keep your key.',[0],2],['Room note','Your room faces the courtyard, away from the road.',[1],2],['Advert','Our hotel has wonderful views.',[],1]]),
    t('Reception desk','Check booking before issuing the key; record arrival after issuing it. One receptionist.',[['Check booking',2,[]],['Issue key',1,[0]],['Record arrival',1,[1]]],7)]),
  m('eng-luggage','Whose suitcase?','English','A2–B1','Find the suitcase according to messages, make a clarification and assemble a kit to return it.','The return service requires both the label and owner confirmation.',[
    d('Identify the case','The owner needs the blue case with a red label.',['Blue case','Red label'],[['Owner message','My suitcase is blue, not black.',[0],2],['Tag register','The owner’s label is red.',[1],2],['Another traveller','Mine is blue too, but has a yellow label.',[],1]]),
    q('Ask for confirmation','Find out the owner of the found suitcase.',['Is this','your blue suitcase','with the red label?']),
    p('Return kits','Prepare exactly four labels and four receipt forms.',['Labels','Receipt forms'],[4,4],[['Return kit',[1,1],4],['Labels only',[2,0],2],['Forms only',[0,2],2]])]),
  m('eng-cafe','The lunch order','English','A2','Read orders, check restrictions, and deliver lunch to your meeting.','Delivery is accepted after check-in at the front desk.',[
    s('Sort the orders','In this assignment, vegetarian excludes meat and fish, but allows dairy products.',['Vegetarian','Contains meat or fish'],[['Cheese and tomato sandwich',0,'Cheese and tomato fit the given condition.'],['Chicken wrap',1,'Chicken - meat.'],['Tuna sandwich',1,'Tuna is a fish.'],['Vegetable soup, no meat stock',0,'The description excludes meat broth.']]),
    d('Confirm the request','The client needs a vegetarian lunch delivered before noon.',['Vegetarian lunch','Before noon'],[['Food message','No meat or fish, please.',[0],2],['Time message','Please deliver before twelve.',[1],2],['Favourite colour','I like green packaging.',[],1]]),
    r('Lunch delivery','Collect the reception stamp ● before reaching the meeting room.',1)]),
  m('eng-exhibition','The pop-up exhibition','English','A2–B1','Read the instructions, assemble the equipment and place the stand according to plan.','The last stand has to be rotated to fit the new mount.',[
    q('Read the setup order','First check the place, then set up a table, then put up a poster.',['Check the space','before you','set up the table','and hang the poster.']),
    p('Equipment request','We need six clips and two stands. Choose complete packs.',['Clips','Stands'],[6,2],[['Display pack',[3,1],2],['Clips pack',[2,0],3],['One stand',[0,1],2]]),
    x('Fit the display','Match the display base to the marked outline. Move, rotate or reflect the base.')]),
  m('eng-interview','The interview day','English','B1','Agree on a working day, check the meeting location and send a message that you are ready.','Confirmation of the meeting must include the location and procedure.',[
    t('One meeting room','Prepare the room before the interview. Write notes afterwards. One room is available.',[['Prepare room',2,[]],['Interview',3,[0]],['Write notes',2,[1]]],10),
    d('Meeting details','The interview is in Room B and starts after the room check.',['Room B','After the room check'],[['Invitation','Please come to Room B.',[0],2],['Schedule note','We start once the room check is complete.',[1],2],['Old invitation','Last month the meeting was in Room A.',[],1]]),
    q('Confirm the plan','Collect confirmation.',['I will wait','in Room B','until the room check','is complete.'])]),
  m('eng-library','The library delivery','English','A2–B1','Deliver documents, check new orders and assemble a set for the reading room.','After delivery, it turned out that the hall needed additional cards.',[
    r('Find the desk','Visit the information point ● before you reach the library desk.',0),
    d('Read the new order','The reading group needs four maps and two guides.',['Four maps','Two guides'],[['Librarian','Please bring four maps.',[0],2],['Group leader','Two guides will be enough.',[1],2],['Old note','Yesterday we needed six maps.',[],1]]),
    p('Prepare the pack','Make the new order exactly; return unused items to storage.',['Maps','Guides'],[4,2],[['Travel kit',[2,1],2],['Map',[1,0],4],['Guide',[0,1],2]])]),
  m('eng-camping','Before the trail','English','A2–B1','Collect equipment as requested, explain the sequence and prepare for the group to leave.','The group is released after checking the equipment.',[
    p('Group request','The group needs eight water bottles and four maps.',['Bottles','Maps'],[8,4],[['Group pack',[2,1],4],['Bottle pair',[2,0],4],['Map pair',[0,2],2]]),
    q('Explain the plan','Collect a message about what needs to be done before leaving.',['We must','check the equipment','before we','leave the camp.']),
    t('Departure tasks','Count the packs before checking them; leave after the check.',[['Count packs',2,[]],['Check equipment',2,[0]],['Register departure',1,[1]]],8)]),
  m('eng-directions','The wrong entrance','English','A2','Explain the way, guide the visitor and distribute the signs according to their meaning.','Similar, but not equivalent, signs appeared at the new entrance.',[
    q('Give directions','First straight, then left at the library.',['Go straight','and then','turn left','at the library.']),
    r('Guide the visitor','Reach the information point ● and then the correct entrance.',3),
    s('Read the signs','Distribute the signs by action.',['Login','Do not enter','Expect'],[['Please come in',0,'Come in - come in.'],['Staff only',1,'Entrance is for employees only.'],['Please wait here',2,'Wait - wait.']])]),
  m('eng-workshop','The community workshop','English','B1','Check the workshop rules, distribute requests and schedule a shared tool.','One instrument cannot be issued to two people at the same time.',[
    d('Workshop rules','Visitors must book a slot and return tools after use.',['Booking required','Tools returned'],[['Booking page','Please book before visiting.',[0],2],['Tool notice','Return every tool when you finish.',[1],2],['Social post','The room looks great.',[],1]]),
    s('Requests and instructions','Distinguish between a request, an instruction and a message about the past.',['Request','Instructions','Past event'],[['Could you lend me a ruler?',0,'Could you enter a request here.'],['Put the ruler back, please.',1,'The speaker asks to perform an action.'],['I returned it yesterday.',2,'Yesterday and returned describe the past.']]),
    t('Shared tool','Inspect the tool before use; record its return afterwards.',[['Inspect',1,[]],['Use',3,[0]],['Record return',1,[1]]],8,[2])]),
  m('eng-news','The neighbourhood newsletter','English','B1','Separate facts from plans, gather news and check sources before release.','The editor requires confirmation of the place and time of the event.',[
    s('Facts and plans','Look at the tense and time expression.',['Past event','Plan','General rule'],[['The club opened yesterday.',0,'Opened and yesterday are the past.'],['We are going to meet tomorrow.',1,'Going to and tomorrow is the plan.'],['The library closes at six every day.',2,'Every day describes a regular rule.']]),
    q('Write the update','Collect a completed message about a past event.',['The club','opened','in the library','yesterday.']),
    d('Check the update','The club opened yesterday in the library.',['Opened yesterday','In the library'],[['Club report','Our opening took place yesterday.',[0],2],['Venue record','The opening event was held in the library.',[1],2],['Future plan','Next month we may move to the park.',[],1]])]),
]

export const languageArtsMissions = [
  m('ela-editor','Editorial of the first issue','Language Arts','5th–7th grade','Analyze the parts of speech, collect the title and prepare the circulation according to the application.','The issue requires both sheets and covers in exact proportions.',[
    s('Words for working in the language','Classify the words in the form indicated.',['Noun','Adjective','Verb'],[['editor',0,'Names the person.'],['bright',1,'Describes a quality.'],['prints',2,'Names the action.'],['number',0,'Names the item.']]),
    q('Heading','Compose a sentence with subject and predicate agreement.',['The new','issue','of the newspaper','is ready.']),
    p('Mini edition','The layout requires 12 pages and 3 covers.',['Pages','Covers'],[12,3],[['One copy',[4,1],3],['Pages of 4',[4,0],3],['Cover',[0,1],3]])]),
  m('ela-quote','Whose quote is this?','Language Arts','7–9 grade','Check the authorship of the educational quote, collect the correct signature and separate the fact from the assessment.','Unconfirmed assessments cannot be transferred to publication.',[
    d('Educational Quote Passport','In the fictional school archive, the phrase belongs to Anna and was recorded at a club meeting.',['Author Anna','Club meeting'],[['Protocol','Anna: “Let’s start with observation.”',[0],2],['Protocol header','Research club meeting.',[1],2],['Retelling','Someone said something similar.',[],1]]),
    q('Exact signature','Compile a signature while maintaining the author and context.',['Anna','said at a club meeting:','“Let’s start with observation.”']),
    s('Fact or estimate?','An assessment expresses an attitude; a fact is verified by recording.',['Fact','Evaluation'],[['Anna is named in the protocol.',0,'This can be checked in the document.'],['This is the best phrase of the meeting.',1,'The best is a value judgment.'],['The meeting took place at the club.',0,'The context is in the title.']])]),
  m('ela-instruction','Instructions for the exhibition','Language Arts','5th–7th grade','Restore the order of the instructions, distinguish between forms of address and place a sign.','The fastening of the sign has been rotated: its shape needs to be preserved.',[
    q('Clear instructions','The instructions must follow the actual procedure.',['Open the box.','Take out the sign.','Check the signature.','Install a sign.']),
    s('Form of statement','Determine what the statement does.',['Inducement','Question','Message'],[['Install a sign.',0,'The imperative form encourages action.'],['Where is the sign?',1,'The question requires an answer.'],['There is a sign at the entrance.',2,'A sentence states a fact.']]),
    x('Label on the mount','Align the flat base of the sign with the outline so that the instructions are at the entrance.')]),
  m('ela-spelling','The spelling post','Language Arts','Grades 5–6','Sort past-tense forms, justify a spelling rule, and print a verified set of word cards.','Only one batch can use the printer at a time.',[
    s('Past-tense spelling','Sort each regular verb by the change used to form its past tense.',['Add -ed','Add -d after final e','Change consonant + y to -ied'],[['walk → walked',0,'Walk takes the regular ending -ed.'],['live → lived',1,'Live already ends in e, so add d.'],['carry → carried',2,'After a consonant, change y to i before adding ed.']]),
    d('Why carried?','Carry becomes carried because y follows a consonant.',['A consonant before y','The -ied ending'],[['Word structure','The letter before y in carry is r, a consonant.',[0],2],['Spelling rule','For a regular verb ending in consonant + y, change y to i and add ed.',[1],2],['Different pattern','Play becomes played: its y follows a vowel.',[],1]]),
    t('Print the cards','Check the words before printing. Pack the cards after printing.',[['Check',2,[]],['Print',2,[0]],['Pack',1,[1]]],8)]),
  m('ela-story','Podcast story','Language Arts','6–8 grade','Collect a coherent story, distribute the recording and mark out time markers.','After editing, check that the time markers agree with the order of events.',[
    q('Cause and effect','Arrange the episodes so that the cause precedes the result.',['It started to rain.','We opened the umbrella.','We reached the library.','We left the umbrella at the entrance.']),
    t('One microphone studio','Preparation before recording; editing after recording.',[['Prepare text',2,[]],['Record',3,[0]],['Edit',2,[1]]],10),
    s('Time markers','Classify the words according to their usual meaning.',['Previously','Now','Later'],[['yesterday',0,'Indicates the past day.'],['today',1,'Indicates the current day.'],['tomorrow',2,'Indicates the next day.']])]),
  m('ela-sign','Library navigation','Language Arts','5th–7th grade','Place a pointer, make an accurate inscription and check where it leads.','The last step requires confirmation of address and destination.',[
    x('Index base','Unfold the mounting base along the mounting contour.'),
    q('Brief caption','Collect a grammatically consistent signature.',['The reading room','is located','on the','second floor.']),
    d('Pointer accuracy','The reading room is located on the second floor.',['This is the reading room','Second floor'],[['Door sign','The door says "Reading Room".',[0],2],['Floor plan','This door is on the second floor plan.',[1],2],['Old plan','Last year\'s diagram may not reflect the move.',[],1]])]),
  m('ela-library','The traveller\'s dictionary','Language Arts','Grades 6–8','Prepare word cards, investigate a word in context, and write a precise explanation.','The definition must fit the context of the journey.',[
    p('Dictionary kit','Collect eight word cards and eight definition cards.',['Words','Definitions'],[8,8],[['Linked pair',[1,1],8],['Four words',[4,0],2],['Four definitions',[0,4],2]]),
    d('What does spring mean here?','In the sentence We stopped at the spring to fill our bottles, spring means a natural water source.',['Water context','Natural source'],[['Sentence','We filled our bottles with fresh water from the spring.',[0],2],['Description','A small flow of water emerges from the ground.',[1],2],['Another meaning','Spring is also the season after winter.',[],1]]),
    q('Precise explanation','Explain the meaning in this context.',['Here,','the word spring','means','a natural source of water.'])]),
  m('ela-report','Reporter on the route','Language Arts','7–9 grade','Confirm the message, get to the editor and clear the text of speculation.','Before publishing, separate verified information from emotional assessments.',[
    d('Two fact notes','A library has opened in the educational city, its first day is Monday.',['Library opened','Opening on Monday'],[['Administration message','The new library has begun work.',[0],2],['Event calendar','The first day of work is Monday.',[1],2],['Comment','This is probably the largest building in the city.',[],1]]),
    r('Transfer material','Visit the checkpoint ● before editing.',2),
    s('Editing a note','Sort the sentences according to the nature of the information.',['Verified fact','Unconfirmed assumption'],[['The library has started working.',0,'This is confirmed by the message.'],['It will surely become the best in the world.',1,'The assumption is not confirmed by documents.'],['The opening was on Monday.',0,'It\'s on the event calendar.']])]),
  m('ela-review','Review without substitution of facts','Language Arts','8–10 grade','Organize the work of the editor, distinguish between thesis and example, check the arguments.','The editor accepts only sources related to the stated thesis.',[
    t('Editorial cycle','Reading before discussion, discussion before release.',[['Read the text',3,[]],['Discuss',2,[0]],['Release',1,[1]]],9),
    s('Parts of reasoning','Define the role of the fragment.',['Thesis','Example','Conclusion'],[['The hero knows how to admit mistakes.',0,'This is a claim that needs to be substantiated.'],['In the third scene he corrected his decision.',1,'This is a specific case from the text.'],['Consequently, he is able to reconsider his actions.',2,'This is the conclusion of the argument.']]),
    d('Check argument','In the fictional story, the hero admitted his mistake and changed his action.',['Admitting a mistake','Corrected Action'],[['Dialogue','“I was mistaken,” said the hero.',[0],2],['Next scene','The hero returned and corrected the incorrect pointer.',[1],2],['Portrait','The hero has a green jacket.',[],1]])]),
  m('ela-agreement','The school noticeboard','Language Arts','Grades 5–7','Match subjects to verbs, build a correct notice, and plan its display area.','The noticeboard has a limited display area and shared boundary.',[
    s('Make the verb agree','Choose the verb form for each subject in the present simple.',['is','are'],[['The poster',0,'The poster is ready: one poster.'],['The signs',1,'The signs are ready: more than one sign.'],['The announcement',0,'The announcement is ready: one announcement.']]),
    q('Noticeboard message','Build a sentence with subject-verb agreement.',['The new','announcement','is','on the board.']),
    g('Display area','Build a connected area of four cells with a perimeter no greater than eight.',4,8)]),
]
